# Configuration for cargo-deny
# See https://embarkstudios.github.io/cargo-deny/

[licenses]
# Don't allow code with unclear licensing
unlicensed = "deny"

# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "GPL-3.0",
]

# Deny these licenses
deny = []

# Warn on licenses that aren't explicitly allowed or denied
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"

[bans]
# Warn if multiple versions of the same crate are used
multiple-versions = "warn"
# Don't warn about these specific crates having multiple versions
skip = []
# Deny specific crates
deny = []

[advisories]
# Deny crates with security vulnerabilities
vulnerability = "deny"
# Warn about unmaintained crates
unmaintained = "warn"
# Warn about yanked crates
yanked = "warn"

[sources]
# Deny crates from unknown registries
unknown-registry = "deny"
# Deny crates from git sources (prefer crates.io)
unknown-git = "warn"
