schema_format_version = 2
name = "MainRepository"

[[definitions]]
schema_format_version = 2
name = "Definition"
subscriptions = [
    "Topic1",
    "Topic2",
    "Topic3",
    "Topic4",
]

[[definitions.models]]
name = "UserV1"
subscriptions = [
    "Topic1",
    "Topic2",
]
family = "User"
version = 1
is_current = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "name"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "age"
type_name = "u8"
kind = "Secondary"

[[definitions.models.fields]]
name = "category"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "DefinitionTwo"
model = "Category"

[[definitions.models]]
name = "User"
subscriptions = [
    "Topic1",
    "Topic2",
]
family = "User"
version = 2
is_current = true

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "first_name"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "last_name"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "age"
type_name = "u8"
kind = "Secondary"

[[definitions.models.fields]]
name = "partner"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "Definition"
model = "User"

[[definitions.models.fields]]
name = "category"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "DefinitionTwo"
model = "Category"

[[definitions.models.fields]]
name = "bio"
type_name = "LargeUserFile"
kind = "Blob"

[[definitions.models.fields]]
name = "another"
type_name = "AnotherLargeUserFile"
kind = "Blob"

[[definitions.models]]
name = "PostV1"
subscriptions = [
    "Topic3",
    "Topic4",
]
family = "Post"
version = 1
is_current = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "title"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "author_id"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "content"
type_name = "String"
kind = "Regular"

[[definitions.models]]
name = "Post"
subscriptions = [
    "Topic3",
    "Topic4",
]
family = "Post"
version = 2
is_current = true

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "title"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "author_id"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "content"
type_name = "String"
kind = "Regular"

[[definitions.models.fields]]
name = "published"
type_name = "bool"
kind = "Regular"

[[definitions.models.fields]]
name = "tags"
type_name = "Vec < String >"
kind = "Regular"

[[definitions.models]]
name = "HeavyModel"
subscriptions = [
    "Topic1",
    "Topic2",
    "Topic3",
    "Topic4",
]
is_current = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "category_label"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "score"
type_name = "u64"
kind = "Secondary"

[[definitions.models.fields]]
name = "creator"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "Definition"
model = "User"

[[definitions.models.fields]]
name = "related_heavy"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "Definition"
model = "HeavyModel"

[[definitions.models.fields]]
name = "attachment"
type_name = "HeavyAttachment"
kind = "Blob"

[[definitions.models.fields]]
name = "name"
type_name = "String"
kind = "Regular"

[[definitions.models.fields]]
name = "title"
type_name = "String"
kind = "Regular"

[[definitions.models.fields]]
name = "matrix"
type_name = "Vec < u64 >"
kind = "Regular"

[[definitions.structs]]
name = "LargeUserFile"
is_tuple = false

[[definitions.structs.fields]]
name = "data"
type_name = "Vec < u8 >"

[[definitions.structs.fields]]
name = "metadata"
type_name = "String"

[[definitions.structs]]
name = "AnotherLargeUserFile"
is_tuple = true

[[definitions.structs.fields]]
name = ""
type_name = "Vec < u8 >"

[[definitions.structs]]
name = "HeavyAttachment"
is_tuple = false

[[definitions.structs.fields]]
name = "mime_type"
type_name = "String"

[[definitions.structs.fields]]
name = "data"
type_name = "Vec < u8 >"

[[definitions.model_history]]
family = "Post"
current_version = 2

[[definitions.model_history.versions]]
version = 1
struct_name = "PostV1"
subscriptions = [
    "Topic3",
    "Topic4",
]
version_hash = "18306954760968958270"
supports_downgrade = false
supports_upgrade = false

[[definitions.model_history.versions.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.model_history.versions.fields]]
name = "title"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "author_id"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "content"
type_name = "String"
kind = "Regular"

[[definitions.model_history.versions]]
version = 2
struct_name = "Post"
subscriptions = [
    "Topic3",
    "Topic4",
]
version_hash = "12940536922446132280"
supports_downgrade = true
supports_upgrade = true

[[definitions.model_history.versions.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.model_history.versions.fields]]
name = "title"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "author_id"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "content"
type_name = "String"
kind = "Regular"

[[definitions.model_history.versions.fields]]
name = "published"
type_name = "bool"
kind = "Regular"

[[definitions.model_history.versions.fields]]
name = "tags"
type_name = "Vec < String >"
kind = "Regular"

[[definitions.model_history.migration_paths]]
from_version = 1
to_version = 2
may_lose_data = false

[[definitions.model_history]]
family = "User"
current_version = 2

[[definitions.model_history.versions]]
version = 1
struct_name = "UserV1"
subscriptions = [
    "Topic1",
    "Topic2",
]
version_hash = "9774471415192068689"
supports_downgrade = false
supports_upgrade = false

[[definitions.model_history.versions.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.model_history.versions.fields]]
name = "name"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "age"
type_name = "u8"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "category"
type_name = "String"
kind = "Relational"

[definitions.model_history.versions.fields.details]
definition = "DefinitionTwo"
model = "Category"

[[definitions.model_history.versions]]
version = 2
struct_name = "User"
subscriptions = [
    "Topic1",
    "Topic2",
]
version_hash = "5563019169600077249"
supports_downgrade = false
supports_upgrade = true

[[definitions.model_history.versions.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.model_history.versions.fields]]
name = "first_name"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "last_name"
type_name = "String"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "age"
type_name = "u8"
kind = "Secondary"

[[definitions.model_history.versions.fields]]
name = "partner"
type_name = "String"
kind = "Relational"

[definitions.model_history.versions.fields.details]
definition = "Definition"
model = "User"

[[definitions.model_history.versions.fields]]
name = "category"
type_name = "String"
kind = "Relational"

[definitions.model_history.versions.fields.details]
definition = "DefinitionTwo"
model = "Category"

[[definitions.model_history.versions.fields]]
name = "bio"
type_name = "LargeUserFile"
kind = "Blob"

[[definitions.model_history.versions.fields]]
name = "another"
type_name = "AnotherLargeUserFile"
kind = "Blob"

[[definitions.model_history.migration_paths]]
from_version = 1
to_version = 2
may_lose_data = false

[[definitions]]
schema_format_version = 2
name = "DefinitionTwo"
subscriptions = ["General"]

[[definitions.models]]
name = "Category"
subscriptions = ["General"]
is_current = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "name"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "description"
type_name = "String"
kind = "Regular"
