[package]
name = "netabase_macros"
version = "0.1.4"
edition = "2024"

[lib]
proc-macro = true

[features]
default = ["schema_export"]
schema_export = ["dep:toml", "dep:serde"]

[dependencies]
syn = { version = "2.0.111", features = ["visit", "visit-mut", "full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
toml = { version = "0.9.10", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
heck = "*"
