schema_format_version = 2
name = "ManagerRepo"

[[definitions]]
schema_format_version = 2
name = "Employee"
subscriptions = []

[[definitions.models]]
name = "User"
subscription_immutable = false
is_current = false
is_libp2p_enabled = false
is_content_addressed = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "name"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "email"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "department"
type_name = "String"
kind = "Regular"

[[definitions.models]]
name = "Shift"
subscription_immutable = false
is_current = false
is_libp2p_enabled = false
is_content_addressed = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "date"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "employee_id"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "Employee"
model = "User"

[[definitions.models.fields]]
name = "hours"
type_name = "u8"
kind = "Regular"

[[definitions]]
schema_format_version = 2
name = "Reports"
subscriptions = []

[[definitions.models]]
name = "Report"
subscription_immutable = false
is_current = false
is_libp2p_enabled = false
is_content_addressed = false

[[definitions.models.fields]]
name = "id"
type_name = "String"
kind = "Primary"

[[definitions.models.fields]]
name = "title"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "report_date"
type_name = "String"
kind = "Secondary"

[[definitions.models.fields]]
name = "created_by"
type_name = "String"
kind = "Relational"

[definitions.models.fields.details]
definition = "Employee"
model = "User"

[[definitions.models.fields]]
name = "content"
type_name = "String"
kind = "Regular"

[[definitions.models.fields]]
name = "is_published"
type_name = "bool"
kind = "Regular"
