use super::PermissionEnumTrait;
use strum::{IntoDiscriminant, IntoEnumIterator};

/// Marker trait indicating a permission grants read access to a definition
///
/// This trait is used for compile-time permission checking. Implement this
/// trait on permission types that should grant read access to specific definitions.
///
/// The trait has no methods or constants - its implementation alone is sufficient
/// to grant compile-time permission at the type level.
///
/// # Type Parameters
/// * `D` - The definition type that this permission grants read access to
///
/// # Example
/// ```ignore
/// // Grant read access to UserDefinition for ManagerPermission
/// impl GrantsReadAccess<UserDefinition> for ManagerPermission {}
/// ```
pub trait GrantsReadAccess<D>
where
    D: IntoDiscriminant,
{
    // Pure marker trait - no methods or constants required
}

/// Marker trait indicating a permission grants write access to a definition
///
/// This trait is used for compile-time permission checking. Implement this
/// trait on permission types that should grant write access to specific definitions.
///
/// The trait has no methods or constants - its implementation alone is sufficient
/// to grant compile-time permission at the type level.
///
/// # Type Parameters
/// * `D` - The definition type that this permission grants write access to
///
/// # Example
/// ```ignore
/// // Grant write access to UserDefinition for ManagerPermission
/// impl GrantsWriteAccess<UserDefinition> for ManagerPermission {}
/// ```
pub trait GrantsWriteAccess<D>
where
    D: IntoDiscriminant,
{
    // Pure marker trait - no methods or constants required
}

/// Helper trait for automatically implementing permission checks
///
/// This trait can be used to generate `GrantsReadAccess` and `GrantsWriteAccess`
/// implementations based on runtime permission checking.
pub trait AutoPermissionChecker: PermissionEnumTrait
where
    <Self as IntoDiscriminant>::Discriminant:
        IntoEnumIterator + std::hash::Hash + Eq + std::fmt::Debug + Clone,
{
    /// Check if this permission type can read from a specific definition
    fn can_read_static<R>(discriminant: &R::Discriminant) -> bool
    where
        R: IntoDiscriminant,
        Self: Sized;

    /// Check if this permission type can write to a specific definition
    fn can_write_static<R>(discriminant: &R::Discriminant) -> bool
    where
        R: IntoDiscriminant,
        Self: Sized;
}

// Note: The actual implementations of GrantsReadAccess and GrantsWriteAccess
// for specific permission types will be generated by the macro system in future phases.
// For now, users implementing custom permissions will need to manually implement these traits.
