use crate::utils::naming::*;
use crate::visitors::model::field::ModelFieldVisitor;
use proc_macro2::TokenStream;
use quote::quote;
use syn::Ident;

/// Generator for key enums (Secondary, Relational, Blob, Subscription, Unified)
pub struct KeyEnumGenerator<'a> {
    visitor: &'a ModelFieldVisitor,
}

impl<'a> KeyEnumGenerator<'a> {
    pub fn new(visitor: &'a ModelFieldVisitor) -> Self {
        Self { visitor }
    }

    /// Generate all key enums for the model
    /// Note: Subscriptions enum is NOT generated here - it's generated by the definition-level macro
    /// because it needs to reference the DefinitionSubscriptions type
    pub fn generate(&self) -> TokenStream {
        let mut output = TokenStream::new();

        output.extend(self.generate_secondary_keys_enum());
        output.extend(self.generate_relational_keys_enum());

        // Subscriptions enum is generated by definition-level macro

        output.extend(self.generate_blob_keys_enum());
        output.extend(self.generate_blob_item_enum());

        output.extend(self.generate_libp2p_provider_key_enum());

        output.extend(self.generate_unified_keys_enum());

        output
    }

    fn generate_libp2p_provider_key_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = libp2p_provider_key_enum_name(model_name);
        let tree_name = tree_name_type(&enum_name);
        let id_type = primary_key_type_name_for_model(self.visitor);
        let blob_keys = blob_keys_enum_name(model_name);
        let relational_keys = relational_keys_enum_name(model_name);

        let enum_doc = format!(
            "LibP2P provider key for `{}` - controls what data to sync in P2P networks.\n\n\
            This enum specifies different synchronization modes when providing or requesting\n\
            this model over a P2P network (libp2p).\n\n\
            # Variants\n\n\
            - `Full(id)`: Sync the complete record including all blobs and relational links\n\
            - `Bare(id)`: Sync only the core record data without blobs or relations\n\
            - `WithBlobs(id, blob_keys)`: Sync the record with specific blob fields\n\
            - `WithRelations(id, relation_keys)`: Sync the record with specific relational links\n\n\
            # P2P Context\n\n\
            These keys are used with libp2p's Kademlia DHT to provide and request records.\n\
            Different modes allow bandwidth optimization by fetching only needed data.",
            model_name
        );

        let tree_doc = format!(
            "TreeName discriminant for `{}` provider key variants.\n\n\
            Represents the different sync modes available in P2P networks.",
            model_name
        );

        quote! {
            #[doc = #tree_doc]
            #[derive(
                Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                serde::Serialize, serde::Deserialize,
                strum::AsRefStr
            )]
            pub enum #tree_name {
                Full,
                Bare,
                WithBlobs,
                WithRelations,
            }

            #[doc = #enum_doc]
            #[derive(
                Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                serde::Serialize, serde::Deserialize,
                Hash
            )]
            pub enum #enum_name {
                /// Sync the complete record including all blobs and relational links.
                Full(#id_type),
                /// Sync only the core record data without blobs or relations.
                Bare(#id_type),
                /// Sync the record with specific blob fields.
                WithBlobs(#id_type, Vec<#blob_keys>),
                /// Sync the record with specific relational links.
                WithRelations(#id_type, Vec<#relational_keys>),
            }

            impl strum::IntoDiscriminant for #enum_name {
                type Discriminant = #tree_name;

                fn discriminant(&self) -> Self::Discriminant {
                    match self {
                        Self::Full(_) => #tree_name::Full,
                        Self::Bare(_) => #tree_name::Bare,
                        Self::WithBlobs(..) => #tree_name::WithBlobs,
                        Self::WithRelations(..) => #tree_name::WithRelations,
                    }
                }
            }
        }
    }

    fn generate_secondary_keys_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = secondary_keys_enum_name(model_name);
        let tree_name = tree_name_type(&enum_name);

        // If no secondary keys, generate an enum with a None variant
        if self.visitor.secondary_keys.is_empty() {
            return quote! {
                /// TreeName discriminant for secondary key variants.
                ///
                /// This model has no secondary keys, so only the None variant is available.
                #[derive(
                    Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                    serde::Serialize, serde::Deserialize,
                    strum::AsRefStr
                )]
                pub enum #tree_name {
                    None
                }

                // Main enum
                #[derive(
                    Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                    serde::Serialize, serde::Deserialize,
                    Hash
                )]
                pub enum #enum_name {
                    None
                }

                // Implement IntoDiscriminant manually
                impl strum::IntoDiscriminant for #enum_name {
                    type Discriminant = #tree_name;

                    fn discriminant(&self) -> Self::Discriminant {
                        #tree_name::None
                    }
                }
            };
        }

        let variants: Vec<_> = self
            .visitor
            .secondary_keys
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                let variant_ident = Ident::new(&variant_name, field.name.span());
                let wrapper_type = field_wrapper_name(model_name, &field.name);

                quote! { #variant_ident(#wrapper_type) }
            })
            .collect();

        let tree_name_variants: Vec<_> = self
            .visitor
            .secondary_keys
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                Ident::new(&variant_name, field.name.span())
            })
            .collect();
        
        let variant_docs: Vec<_> = self
            .visitor
            .secondary_keys
            .iter()
            .map(|field| {
                let field_name = &field.name;
                let ty = &field.ty;
                format!("Secondary index on the `{}` field (type: `{}`)", 
                    field_name, 
                    quote!(#ty).to_string())
            })
            .collect();

        let enum_doc = format!(
            "Secondary key variants for `{}`.\n\n\
            This enum is used to specify which secondary index to query when performing lookups.\n\
            Each variant corresponds to a field marked with `#[secondary_key]` in the model.\n\n\
            # Example\n\n\
            ```rust\n\
            # use netabase_store::doc_example::*;\n\
            // Create a secondary key for querying\n\
            let key = UserSecondaryKeys::Email(UserEmail(\"alice@example.com\".into()));\n\
            \n\
            // The key can be used in database queries:\n\
            // let users: Vec<User> = txn.read_secondary(&key)?;\n\
            ```\n\n\
            # Available Variants\n\n\
            {}",
            model_name,
            variant_docs.iter().enumerate()
                .map(|(i, doc)| format!("- `{}`: {}", tree_name_variants[i], doc))
                .collect::<Vec<_>>()
                .join("\n")
        );

        let tree_doc = format!(
            "TreeName discriminant for `{}` secondary key variants.\n\n\
            Used internally for Merkle tree organization and serialization.",
            model_name
        );

        quote! {
            #[doc = #tree_doc]
            #[derive(
                Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                serde::Serialize, serde::Deserialize,
                strum::AsRefStr
            )]
            pub enum #tree_name {
                #(#tree_name_variants),*
            }

            #[doc = #enum_doc]
            #[derive(
                Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                serde::Serialize, serde::Deserialize,
                Hash
            )]
            pub enum #enum_name {
                #(#variants),*
            }

            // Implement IntoDiscriminant manually
            impl strum::IntoDiscriminant for #enum_name {
                type Discriminant = #tree_name;

                fn discriminant(&self) -> Self::Discriminant {
                    match self {
                        #(#enum_name::#tree_name_variants(_) => #tree_name::#tree_name_variants),*
                    }
                }
            }
        }
    }

    fn generate_relational_keys_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = relational_keys_enum_name(model_name);
        let tree_name = tree_name_type(&enum_name);

        // If no relational keys, generate an enum with a None variant
        if self.visitor.relational_keys.is_empty() {
            return quote! {
                // TreeName discriminant enum
                #[derive(
                    Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                    serde::Serialize, serde::Deserialize,
                    strum::AsRefStr
                )]
                pub enum #tree_name {
                    None
                }

                // Main enum
                #[derive(
                    Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                    serde::Serialize, serde::Deserialize,
                    Hash
                )]
                pub enum #enum_name {
                    None
                }

                // Implement IntoDiscriminant manually
                impl strum::IntoDiscriminant for #enum_name {
                    type Discriminant = #tree_name;

                    fn discriminant(&self) -> Self::Discriminant {
                        #tree_name::None
                    }
                }
            };
        }

        let variants: Vec<_> = self
            .visitor
            .relational_keys
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                let variant_ident = Ident::new(&variant_name, field.name.span());
                let wrapper_type = field_wrapper_name(model_name, &field.name);

                quote! { #variant_ident(#wrapper_type) }
            })
            .collect();

        let tree_name_variants: Vec<_> = self
            .visitor
            .relational_keys
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                Ident::new(&variant_name, field.name.span())
            })
            .collect();

        let variant_docs: Vec<_> = self
            .visitor
            .relational_keys
            .iter()
            .map(|field| {
                let field_name = &field.name;
                let ty = &field.ty;
                format!("Relational link on the `{}` field (type: `{}`)", 
                    field_name,
                    quote!(#ty).to_string())
            })
            .collect();

        let enum_doc = format!(
            "Relational key variants for `{}`.\n\n\
            This enum is used to specify which relational field to query when traversing links between models.\n\
            Each variant corresponds to a field marked with `#[link(Definition, TargetModel)]` in the model.\n\n\
            # Generated Variants\n\n\
            {}",
            model_name,
            variant_docs.iter().enumerate()
                .map(|(i, doc)| format!("- `{}`: {}", tree_name_variants[i], doc))
                .collect::<Vec<_>>()
                .join("\n")
        );

        let tree_doc = format!(
            "TreeName discriminant for `{}` relational key variants.\n\n\
            Used internally for Merkle tree organization and link tracking.",
            model_name
        );

        quote! {
            #[doc = #tree_doc]
            #[derive(
                Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                serde::Serialize, serde::Deserialize,
                strum::AsRefStr
            )]
            pub enum #tree_name {
                #(#tree_name_variants),*
            }

            #[doc = #enum_doc]
            #[derive(
                Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                serde::Serialize, serde::Deserialize,
                Hash
            )]
            pub enum #enum_name {
                #(#variants),*
            }

            // Implement IntoDiscriminant manually
            impl strum::IntoDiscriminant for #enum_name {
                type Discriminant = #tree_name;

                fn discriminant(&self) -> Self::Discriminant {
                    match self {
                        #(#enum_name::#tree_name_variants(_) => #tree_name::#tree_name_variants),*
                    }
                }
            }
        }
    }

    fn generate_subscriptions_enum(&self) -> TokenStream {
        // ... (unchanged, still unused here)
        TokenStream::new()
    }

    fn generate_blob_keys_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = blob_keys_enum_name(model_name);
        let tree_name = tree_name_type(&enum_name);
        let id_type = primary_key_type_name_for_model(self.visitor);

        // If no blob fields, generate an enum with a None variant
        if self.visitor.blob_fields.is_empty() {
            return quote! {
                // TreeName discriminant enum
                #[derive(
                    Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                    serde::Serialize, serde::Deserialize,
                    strum::AsRefStr
                )]
                pub enum #tree_name {
                    None
                }

                // Main enum
                #[derive(
                    Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                    serde::Serialize, serde::Deserialize,
                    Hash
                )]
                pub enum #enum_name {
                    None
                }

                // Implement IntoDiscriminant manually
                impl strum::IntoDiscriminant for #enum_name {
                    type Discriminant = #tree_name;

                    fn discriminant(&self) -> Self::Discriminant {
                        #tree_name::None
                    }
                }
            };
        }

        let variants: Vec<_> = self
            .visitor
            .blob_fields
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                let variant_ident = Ident::new(&variant_name, field.name.span());

                quote! { #variant_ident { owner: #id_type } }
            })
            .collect();

        let tree_name_variants: Vec<_> = self
            .visitor
            .blob_fields
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                Ident::new(&variant_name, field.name.span())
            })
            .collect();

        let variant_docs: Vec<_> = self
            .visitor
            .blob_fields
            .iter()
            .map(|field| {
                let field_name = &field.name;
                let ty = &field.ty;
                format!("Blob field `{}` (type: `{}`) - Large binary data stored separately",
                    field_name,
                    quote!(#ty).to_string())
            })
            .collect();

        let enum_doc = format!(
            "Blob key variants for `{}`.\n\n\
            This enum is used to specify which blob field to read or write. Blobs are large binary\n\
            data (like images, videos, documents) that are stored separately from the main model data\n\
            and accessed through this enum.\n\n\
            Each variant corresponds to a field marked with `#[blob]` in the model.\n\n\
            # Example\n\n\
            ```rust\n\
            # use netabase_store::doc_example::*;\n\
            // Create a blob key\n\
            let owner_id = AuthorID(\"author123\".into());\n\
            let blob_key = AuthorBlobKeys::ProfilePicture {{ owner: owner_id.clone() }};\n\
            \n\
            // Use for blob operations:\n\
            // txn.write_blob(&blob_key, image_bytes)?;\n\
            // let data: Vec<u8> = txn.read_blob(&blob_key)?;\n\
            ```\n\n\
            # Available Blobs\n\n\
            {}\n\n\
            # Storage Details\n\n\
            Blobs are automatically chunked for efficient storage and can be streamed\n\
            for large files. They are stored in separate tables from the main model data.",
            model_name,
            variant_docs.iter().enumerate()
                .map(|(i, doc)| format!("- `{}`: {}", tree_name_variants[i], doc))
                .collect::<Vec<_>>()
                .join("\n")
        );

        let tree_doc = format!(
            "TreeName discriminant for `{}` blob key variants.\n\n\
            Used internally for Merkle tree organization and blob storage management.",
            model_name
        );

        quote! {
            #[doc = #tree_doc]
            #[derive(
                Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                serde::Serialize, serde::Deserialize,
                strum::AsRefStr
            )]
            pub enum #tree_name {
                #(#tree_name_variants),*
            }

            #[doc = #enum_doc]
            #[derive(
                Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                serde::Serialize, serde::Deserialize,
                Hash
            )]
            pub enum #enum_name {
                #(#variants),*
            }

            // Implement IntoDiscriminant manually
            impl strum::IntoDiscriminant for #enum_name {
                type Discriminant = #tree_name;

                fn discriminant(&self) -> Self::Discriminant {
                    match self {
                        #(#enum_name::#tree_name_variants { .. } => #tree_name::#tree_name_variants),*
                    }
                }
            }
        }
    }

    fn generate_blob_item_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = blob_item_enum_name(model_name);

        // If no blob fields, generate an empty struct (not an enum)
        if self.visitor.blob_fields.is_empty() {
            return quote! {
                #[derive(
                    Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                    serde::Serialize, serde::Deserialize
                )]
                pub struct #enum_name;
            };
        }

        let variants: Vec<_> = self
            .visitor
            .blob_fields
            .iter()
            .map(|field| {
                let variant_name = to_pascal_case(&field.name.to_string());
                let variant_ident = Ident::new(&variant_name, field.name.span());
                let field_type = &field.ty;

                quote! { #variant_ident(<#field_type as netabase_store::blob::NetabaseBlobItem>::Blobs) }
            })
            .collect();

        quote! {
            #[derive(
                Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
                serde::Serialize, serde::Deserialize
            )]
            pub enum #enum_name {
                #(#variants),*
            }
        }
    }

    fn generate_unified_keys_enum(&self) -> TokenStream {
        let model_name = &self.visitor.model_name;
        let enum_name = unified_keys_enum_name(model_name);
        let id_type = primary_key_type_name_for_model(self.visitor);

        let mut variants = vec![quote! { Primary(#id_type) }];

        // Secondary
        let secondary_enum = secondary_keys_enum_name(model_name);
        variants.push(quote! { Secondary(#secondary_enum) });

        // Relational
        let relational_enum = relational_keys_enum_name(model_name);
        variants.push(quote! { Relational(#relational_enum) });

        // Subscription
        let subscription_enum = subscriptions_enum_name(model_name);
        variants.push(quote! { Subscription(#subscription_enum) });

        // Blob
        let blob_enum = blob_keys_enum_name(model_name);
        variants.push(quote! { Blob(#blob_enum) });

        quote! {
            #[derive(
                Clone, Eq, PartialEq, PartialOrd, Ord, Debug,
                serde::Serialize, serde::Deserialize,
                Hash
            )]
            pub enum #enum_name {
                #(#variants),*
            }
        }
    }
}

/// Helper function to convert snake_case to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}
