//! Repository-level store management for multi-definition databases.
//!
//! This module provides `RedbRepositoryStore` which manages multiple definition stores
//! within a single repository, enabling inter-definitional communication through
//! `RelationalLink`s.
//!
//! # Folder Structure
//!
//! A repository creates a parent folder containing a subfolder for each definition:
//!
//! ```text
//! my_repository/
//! ├── repository.toml           # Repository-level metadata
//! ├── Definition1/
//! │   ├── data.redb            # Definition1's database
//! │   └── schema.toml          # Definition1's schema
//! ├── Definition2/
//! │   ├── data.redb            # Definition2's database
//! │   └── schema.toml          # Definition2's schema
//! └── ...
//! ```
//!
//! # Repository Metadata
//!
//! The `repository.toml` file contains:
//! - Repository name and version
//! - List of all definitions in the repository
//! - Inter-definition relationship mapping
//! - Schema compatibility information
//!
//! A minimal example looks like:
//!
//! ```toml
//! [repository]
//! name = "MainRepo"
//! version = 1
//!
//! [[definitions]]
//! name = "UserDef"
//! path = "UserDef/schema.toml"
//!
//! [[definitions]]
//! name = "PostDef"
//! path = "PostDef/schema.toml"
//!
//! [[links]]
//! from = "PostDef.Post.author"
//! to = "UserDef.User.id"
//! ```
//!
//! # Initialization Process
//!
//! 1. Create repository root folder
//! 2. For each definition:
//!    a. Create definition subfolder
//!    b. Initialize redb database
//!    c. Export schema.toml
//! 3. Generate `repository.toml` metadata describing all definitions
//!
//! ## On-Disk Layout
//!
//! A repository folder created by `RedbRepositoryStore` looks like:
//!
//! - `repository.toml` – high-level repository metadata
//! - `<DefinitionA>/data.redb` – redb database for DefinitionA
//! - `<DefinitionA>/schema.toml` – exported schema for DefinitionA
//! - `<DefinitionB>/data.redb` – redb database for DefinitionB
//! - `<DefinitionB>/schema.toml` – exported schema for DefinitionB
//!
//! This layout mirrors the logical structure generated by
//! `#[netabase_definition]` and `#[netabase_repository]`, so schema
//! files can be inspected, versioned, or shipped independently of the
//! actual data files.
//!
//! # Thread Safety
//!
//! Each definition's database is managed by redb which provides ACID guarantees.
//! Multiple threads can safely access different definitions concurrently.
//! Access to the same definition is serialized by redb's transaction system.
//!
//! # Example
//!
//! See [tests/repository_comprehensive.rs](../../../tests/repository_comprehensive.rs)
//! for complete working examples of repository creation and usage.
//!
//! ```rust,no_run
//! # // Repository usage is demonstrated in tests/repository_comprehensive.rs
//! # // This doctest validates the module compiles
//! use netabase_store::databases::redb::repository::RedbRepositoryStore;
//! ```

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use redb::ReadableDatabase;

use crate::errors::{NetabaseError, NetabaseResult};
use crate::traits::registry::definition::redb_definition::RedbDefinition;
use crate::traits::registry::repository::NetabaseRepository;

/// The name of the repository metadata file.
const REPOSITORY_META_FILE: &str = "repository.toml";

/// Trait for types that can provide definition store paths and initialization.
///
/// This trait is implemented by the `#[netabase_repository]` macro to generate
/// the logic for creating and accessing individual definition stores.
pub trait RedbRepositoryDefinitions: NetabaseRepository {
    /// Get the list of definition names in this repository.
    fn definition_names() -> &'static [&'static str];

    /// Initialize all definition stores in the given repository folder.
    ///
    /// This creates the folder structure and initializes each definition's
    /// database and schema files.
    fn init_definition_stores(repo_path: &Path) -> NetabaseResult<()>;
}

/// Repository-level store that manages multiple definition stores.
///
/// This struct holds the repository folder path and provides access to
/// individual definition stores. It ensures that all definitions are
/// initialized when the repository is created.
pub struct RedbRepositoryStore<R: RedbRepositoryDefinitions> {
    /// Path to the repository folder.
    path: PathBuf,
    /// Repository marker (zero-sized).
    _marker: std::marker::PhantomData<R>,
    /// Cached database handles for each definition, keyed by definition name.
    databases: HashMap<&'static str, Arc<redb::Database>>,
}

impl<R: RedbRepositoryDefinitions> RedbRepositoryStore<R> {
    /// Create or open a repository store at the given path.
    ///
    /// This will:
    /// 1. Create the repository folder if it doesn't exist
    /// 2. Create subfolders for each definition
    /// 3. Initialize each definition's database and schema
    /// 4. Write/update the repository metadata file
    ///
    /// # Arguments
    ///
    /// * `path` - Path to the repository folder
    ///
    /// # Example
    ///
    /// See [tests/repository_comprehensive.rs](../../../tests/repository_comprehensive.rs).
    ///
    /// ```rust,no_run
    /// let store = RedbRepositoryStore::<MyRepo>::new("./my_repo")?;
    /// ```
    pub fn new<P: AsRef<Path>>(path: P) -> NetabaseResult<Self> {
        let repo_path = path.as_ref().to_path_buf();

        // Create the repository folder
        if !repo_path.exists() {
            std::fs::create_dir_all(&repo_path).map_err(|e| {
                NetabaseError::IoError(format!(
                    "Failed to create repository folder {:?}: {}",
                    repo_path, e
                ))
            })?;
        }

        // Initialize all definition stores
        R::init_definition_stores(&repo_path)?;

        // Write repository metadata
        let meta_path = repo_path.join(REPOSITORY_META_FILE);
        let meta_content = Self::generate_repository_metadata();
        std::fs::write(&meta_path, &meta_content).map_err(|e| {
            NetabaseError::IoError(format!(
                "Failed to write repository metadata {:?}: {}",
                meta_path, e
            ))
        })?;

        // Open all definition databases
        let mut databases = HashMap::new();
        for def_name in R::definition_names() {
            let def_path = repo_path.join(def_name).join("data.redb");
            let db = redb::Database::create(&def_path)
                .map_err(|e| NetabaseError::RedbError(e.into()))?;
            databases.insert(*def_name, Arc::new(db));
        }

        Ok(Self {
            path: repo_path,
            _marker: std::marker::PhantomData,
            databases,
        })
    }

    /// Get the path to the repository folder.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Get the path to a specific definition's folder.
    pub fn definition_path(&self, definition_name: &str) -> PathBuf {
        self.path.join(definition_name)
    }

    /// Get a reference to a definition's database.
    ///
    /// # Arguments
    ///
    /// * `definition_name` - The name of the definition
    ///
    /// # Returns
    ///
    /// The database handle, or an error if the definition doesn't exist.
    pub fn database(&self, definition_name: &str) -> NetabaseResult<&Arc<redb::Database>> {
        self.databases.get(definition_name).ok_or_else(|| {
            NetabaseError::DefinitionNotFound(format!(
                "Definition '{}' not found in repository '{}'",
                definition_name,
                R::name()
            ))
        })
    }

    /// Get the names of all definitions in this repository.
    pub fn definition_names(&self) -> &'static [&'static str] {
        R::definition_names()
    }

    /// Generate repository metadata TOML content.
    fn generate_repository_metadata() -> String {
        let def_names: Vec<_> = R::definition_names().iter().collect();

        format!(
            r#"# Repository: {}
# Generated by netabase_store

[repository]
name = "{}"
definition_count = {}
model_count = {}

[definitions]
names = {:?}
"#,
            R::name(),
            R::name(),
            R::definition_count(),
            R::model_count(),
            def_names
        )
    }

    /// Check if all definition databases are healthy.
    pub fn check_health(&self) -> NetabaseResult<()> {
        for def_name in R::definition_names() {
            let db: &Arc<redb::Database> = self.database(def_name)?;
            // Try to begin a read transaction to verify database is accessible
            // Arc<Database> derefs to Database which has begin_read
            let _txn = (**db)
                .begin_read()
                .map_err(NetabaseError::RedbTransactionError)?;
        }
        Ok(())
    }
}

/// Repository-level transaction that spans multiple definitions.
///
/// This allows reading and writing across definitions within a single
/// transaction context. Changes are only committed when all operations
/// succeed across all definitions.
///
/// # Note
///
/// Currently, redb doesn't support true distributed transactions across
/// multiple database files. This implementation provides logical grouping
/// and sequential commits. For true ACID across definitions, consider
/// using a single database file with table prefixes.
pub struct RedbRepositoryTransaction<'repo, R: RedbRepositoryDefinitions> {
    store: &'repo RedbRepositoryStore<R>,
    /// Write transactions for each definition that has been accessed.
    write_transactions: HashMap<&'static str, redb::WriteTransaction>,
    /// Whether this is a write transaction.
    is_write: bool,
}

impl<'repo, R: RedbRepositoryDefinitions> RedbRepositoryTransaction<'repo, R> {
    /// Create a new read-only repository transaction.
    pub fn new_read(store: &'repo RedbRepositoryStore<R>) -> NetabaseResult<Self> {
        Ok(Self {
            store,
            write_transactions: HashMap::new(),
            is_write: false,
        })
    }

    /// Create a new read-write repository transaction.
    pub fn new_write(store: &'repo RedbRepositoryStore<R>) -> NetabaseResult<Self> {
        // Pre-acquire write transactions for all definitions
        let mut write_transactions = HashMap::new();
        for def_name in R::definition_names() {
            let db = store.database(def_name)?;
            let txn = db
                .begin_write()
                .map_err(|e| NetabaseError::RedbError(e.into()))?;
            write_transactions.insert(*def_name, txn);
        }

        Ok(Self {
            store,
            write_transactions,
            is_write: true,
        })
    }

    /// Get a read transaction for a specific definition.
    ///
    /// # Type Parameters
    ///
    /// * `D` - The definition type to get a transaction for
    #[allow(clippy::multiple_bound_locations)]
    pub fn read_definition<D: RedbDefinition>(&self) -> NetabaseResult<redb::ReadTransaction>
    where
        D::Discriminant: 'static + std::fmt::Debug,
        D: Clone,
    {
        let def_name = D::definition_name();
        let def_name_str = format!("{:?}", def_name);
        let db = self.store.database(&def_name_str)?;
        (**db)
            .begin_read()
            .map_err(NetabaseError::RedbTransactionError)
    }

    /// Get the write transaction for a specific definition.
    ///
    /// # Type Parameters
    ///
    /// * `D` - The definition type to get a transaction for
    ///
    /// # Panics
    ///
    /// Panics if this is not a write transaction.
    pub fn write_definition(
        &mut self,
        definition_name: &'static str,
    ) -> NetabaseResult<&mut redb::WriteTransaction> {
        if !self.is_write {
            return Err(NetabaseError::TransactionError(
                "Cannot get write transaction from read-only repository transaction".to_string(),
            ));
        }

        self.write_transactions
            .get_mut(definition_name)
            .ok_or_else(|| {
                NetabaseError::DefinitionNotFound(format!(
                    "Definition '{}' not found in repository transaction",
                    definition_name
                ))
            })
    }

    /// Commit all pending writes across all definitions.
    ///
    /// This commits each definition's transaction sequentially.
    /// If any commit fails, the remaining definitions are not committed.
    pub fn commit(self) -> NetabaseResult<()> {
        if !self.is_write {
            return Ok(());
        }

        for (def_name, txn) in self.write_transactions {
            txn.commit().map_err(|e| {
                NetabaseError::RedbError(redb::Error::Io(std::io::Error::other(
                    format!("Failed to commit transaction for '{}': {}", def_name, e),
                )))
            })?;
        }

        Ok(())
    }

    /// Check if this is a write transaction.
    pub fn is_write(&self) -> bool {
        self.is_write
    }
}

impl<R: RedbRepositoryDefinitions> RedbRepositoryStore<R> {
    /// Begin a read-only repository transaction.
    pub fn begin_read(&self) -> NetabaseResult<RedbRepositoryTransaction<'_, R>> {
        RedbRepositoryTransaction::new_read(self)
    }

    /// Begin a read-write repository transaction.
    pub fn begin_write(&self) -> NetabaseResult<RedbRepositoryTransaction<'_, R>> {
        RedbRepositoryTransaction::new_write(self)
    }
}

// ============================================================================
// Table Caching Support
// ============================================================================

use std::any::TypeId;
use std::cell::RefCell;

/// Key for cached table lookups.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct TableCacheKey {
    /// Definition type ID
    pub definition_id: TypeId,
    /// Table name
    pub table_name: String,
}

/// Cached table handle for efficient repeated access.
///
/// This avoids reopening tables on every read/write operation within
/// a transaction, which is especially important for relational links
/// that may need to access multiple tables.
pub struct TableCache {
    /// Set of table names that have been opened in this transaction.
    /// The actual table handles are managed by the transaction itself.
    opened_tables: RefCell<std::collections::HashSet<TableCacheKey>>,
}

impl TableCache {
    /// Create a new empty table cache.
    pub fn new() -> Self {
        Self {
            opened_tables: RefCell::new(std::collections::HashSet::new()),
        }
    }

    /// Check if a table is already cached.
    pub fn is_cached(&self, key: &TableCacheKey) -> bool {
        self.opened_tables.borrow().contains(key)
    }

    /// Mark a table as cached.
    pub fn mark_cached(&self, key: TableCacheKey) {
        self.opened_tables.borrow_mut().insert(key);
    }

    /// Get the number of cached tables.
    pub fn len(&self) -> usize {
        self.opened_tables.borrow().len()
    }

    /// Check if the cache is empty.
    pub fn is_empty(&self) -> bool {
        self.opened_tables.borrow().is_empty()
    }
}

impl Default for TableCache {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Enhanced Repository Transaction with Definition Dispatch
// ============================================================================

use crate::traits::registry::models::model::ModelToDefKey;

impl<'repo, R: RedbRepositoryDefinitions> RedbRepositoryTransaction<'repo, R> {
    /// Read a model from a specific definition using the definition's dispatch mechanism.
    ///
    /// This method uses the definition's `dispatch_read` to read a model by its
    /// primary key, leveraging the macro-generated code for type safety.
    ///
    /// # Type Parameters
    ///
    /// * `D` - The definition type containing the model
    /// * `M` - The model type to read
    ///
    /// # Arguments
    ///
    /// * `key` - The primary key of the model to read
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// // Read a User from UserDef within the repository transaction
    /// let user: Option<User> = repo_txn.read_model::<UserDef, User>(&user_id)?;
    /// ```
    #[allow(clippy::type_complexity)]
    pub fn read_model_from_definition<D, M>(
        &self,
        pk: <M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Primary,
    ) -> NetabaseResult<Option<M>>
    where
        D: RedbDefinition + Clone + serde::Serialize + for<'de> serde::Deserialize<'de> + 'static,
        D::Discriminant: 'static + std::fmt::Debug,
        M: ModelToDefKey<D> + Clone,
        <<M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
        <<M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
        <<M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
        <<M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
        <<M::Keys as crate::traits::registry::models::keys::NetabaseModelKeys<D, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    {
        // Convert the model's primary key to definition-level key
        let def_key = M::primary_to_def_key(pk);
        
        // Get the definition name
        let def_name = D::definition_name();
        
        // Get database for this definition
        let db = self.store.database(&def_name)?;
        
        // Begin a read transaction
        let read_txn = (**db).begin_read()
            .map_err(NetabaseError::RedbTransactionError)?;
        
        // Use the definition's dispatch_read
        // Note: This requires wrapping the raw redb transaction
        // For now, we'll use a simplified approach
        // TODO: Create proper transaction wrapper for dispatch_read
        
        // Fallback: Since dispatch_read needs our custom transaction type,
        // and we only have raw redb transaction here, we need to handle this differently.
        // For repository-level access, we should either:
        // 1. Store RedbTransaction wrappers per definition
        // 2. Or use the dispatch mechanism differently
        
        // For now, return an error indicating this needs the proper transaction
        Err(NetabaseError::TransactionError(
            "Repository-level model reading requires proper transaction wrapping. \
             Use RedbRepositoryStore::with_definition() to get a typed transaction.".to_string()
        ))
    }
}

// ============================================================================
// RelationalLink Hydration Support
// ============================================================================

// Note: Hydration of RelationalLinks at the repository level requires
// proper integration with the definition's dispatch_read mechanism.
// 
// The recommended approach for now is:
// 1. Use RedbRepositoryStore::with_definition::<D>() to get a typed store
// 2. Use that store's transaction to read models
// 3. Use RelationalLink::from_loaded() to create hydrated links
//
// Example:
// ```rust,no_run
// let store = repo_store.with_definition::<TargetDef>()?;
// let txn = store.begin_read()?;
// if let Some(model) = txn.read::<TargetModel>(&link.get_primary_key())? {
//     let hydrated = RelationalLink::from_loaded(link.get_primary_key().clone(), model);
// }
// ```
//
// TODO: Implement proper repository-level transaction that can dispatch
// reads to multiple definitions while maintaining table caching.

// ============================================================================
// Definition-Specific Store Access
// ============================================================================

use crate::databases::redb::transaction::RedbTransaction;

impl<R: RedbRepositoryDefinitions> RedbRepositoryStore<R> {
    /// Get a definition-specific store from the repository.
    /// 
    /// This allows creating `RedbTransaction<D>` for any definition in the repository,
    /// enabling inter-definition relational link hydration.
    ///
    /// # Type Parameters
    ///
    /// * `D` - The definition type to access
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// let repo = RedbRepositoryStore::<MyRepo>::new("./repo")?;
    /// 
    /// // Get a transaction for the UserDef definition
    /// let user_txn = repo.begin_read_for::<UserDef>()?;
    /// let user: Option<User> = user_txn.read(&user_id)?;
    /// ```
    pub fn begin_read_for<'repo, D>(&'repo self) -> NetabaseResult<RedbTransaction<'repo, D>>
    where
        D: RedbDefinition + Clone + 'static,
        D::Discriminant: 'static + std::fmt::Debug,
    {
        let def_name = D::definition_name();
        let db = self.database(&def_name)?;
        RedbTransaction::new_read(db)
    }
    
    /// Begin a write transaction for a specific definition.
    ///
    /// # Type Parameters
    ///
    /// * `D` - The definition type to access
    pub fn begin_write_for<'repo, D>(&'repo self) -> NetabaseResult<RedbTransaction<'repo, D>>
    where
        D: RedbDefinition + Clone + 'static,
        D::Discriminant: 'static + std::fmt::Debug,
    {
        let def_name = D::definition_name();
        let db = self.database(&def_name)?;
        RedbTransaction::new_write(db)
    }
    
    /// Get a raw database reference for a definition by type.
    ///
    /// This is useful for advanced use cases where you need direct access
    /// to the underlying redb database.
    pub fn database_for<D>(&self) -> NetabaseResult<&Arc<redb::Database>>
    where
        D: RedbDefinition + 'static,
        D::Discriminant: 'static + std::fmt::Debug,
    {
        let def_name = D::definition_name();
        self.database(&def_name)
    }
}

// ============================================================================
// RelationalLink Repository-Level Hydration
// ============================================================================

use crate::relational::{RelationalLink, RelationalLinkError};
use crate::traits::registry::models::model::NetabaseModel;
use crate::traits::registry::models::keys::NetabaseModelKeys;
use crate::traits::registry::repository::InRepository;
use crate::traits::registry::definition::NetabaseDefinition;
use crate::databases::redb::transaction::crud::RedbModelCrud;
use crate::traits::registry::models::model::redb_model::RedbNetbaseModel;

/// Extension trait for hydrating relational links at the repository level.
///
/// This enables hydration of `RelationalLink<R, SourceD, TargetD, M>` where
/// `SourceD != TargetD` (cross-definition links).
pub trait RepositoryHydrate<'data, R, SourceD, TargetD, M>
where
    R: NetabaseRepository,
    SourceD: NetabaseDefinition + InRepository<R> + 'static,
    SourceD::Discriminant: std::fmt::Debug,
    TargetD: NetabaseDefinition + InRepository<R> + 'static,
    TargetD::Discriminant: std::fmt::Debug,
    M: NetabaseModel<TargetD>,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    /// Hydrate this link using a repository store.
    ///
    /// This method works for both same-definition and cross-definition links,
    /// making it the most general hydration method.
    ///
    /// # Arguments
    ///
    /// * `repo` - The repository store containing both source and target definitions
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// // Cross-definition link: Post (in PostDef) -> Author (in UserDef)
    /// let repo = RedbRepositoryStore::<MyRepo>::new("./repo")?;
    /// let post: Post = /* read post */;
    /// 
    /// // Hydrate the cross-definition author link
    /// let hydrated = post.author.hydrate_from_repo(&repo)?;
    /// let author = hydrated.get_model().unwrap();
    /// ```
    fn hydrate_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Result<RelationalLink<'data, R, SourceD, TargetD, M>, RelationalLinkError>
    where
        RD: RedbRepositoryDefinitions;
}

impl<'data, R, SourceD, TargetD, M> RepositoryHydrate<'data, R, SourceD, TargetD, M>
    for RelationalLink<'data, R, SourceD, TargetD, M>
where
    R: NetabaseRepository,
    SourceD: NetabaseDefinition + InRepository<R> + 'static,
    SourceD::Discriminant: std::fmt::Debug,
    TargetD: RedbDefinition + InRepository<R> + Clone + 'static,
    TargetD::Discriminant: std::fmt::Debug + 'static,
    M: NetabaseModel<TargetD> + Clone,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Primary: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Relational: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Blob: redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription: 'static,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    for<'a> <M::Keys as NetabaseModelKeys<TargetD, M>>::Primary: std::borrow::Borrow<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Primary as redb::Value>::SelfType<'a>>,
    for<'a> <M::Keys as NetabaseModelKeys<TargetD, M>>::Blob: std::borrow::Borrow<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as redb::Value>::SelfType<'a>>,
    for<'a> <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem: std::borrow::Borrow<<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem as redb::Value>::SelfType<'a>>,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem: redb::Key + 'static,
    TargetD::SubscriptionKeys: redb::Key + 'static,
    for<'db> M: RedbNetbaseModel<'db, TargetD> + RedbModelCrud<'db, TargetD>,
    for<'db, 'a> <M as RedbNetbaseModel<'db, TargetD>>::TableV: redb::Value<SelfType<'a> = M>,
{
    fn hydrate_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Result<RelationalLink<'data, R, SourceD, TargetD, M>, RelationalLinkError>
    where
        RD: RedbRepositoryDefinitions,
    {
        // If already hydrated, return as-is
        if self.get_model().is_some() {
            return Ok(self);
        }
        
        // Clone the primary key
        let pk = self.get_primary_key().clone();
        
        // Begin a read transaction for the target definition
        let txn = repo.begin_read_for::<TargetD>()
            .map_err(|_| RelationalLinkError::NotFound)?;
        
        // Read the model using read_by_key (takes owned key)
        let model = txn.read_by_key::<M>(pk.clone())
            .map_err(|_| RelationalLinkError::NotFound)?
            .ok_or(RelationalLinkError::NotFound)?;
        
        // Return an owned link with the loaded model
        Ok(RelationalLink::from_loaded(pk, model))
    }
}

/// Extension trait for hydrating vectors of cross-definition relational links.
pub trait RepositoryHydrateVec<'data, R, SourceD, TargetD, M>
where
    R: NetabaseRepository,
    SourceD: NetabaseDefinition + InRepository<R> + 'static,
    SourceD::Discriminant: std::fmt::Debug,
    TargetD: NetabaseDefinition + InRepository<R> + 'static,
    TargetD::Discriminant: std::fmt::Debug,
    M: NetabaseModel<TargetD>,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    /// Hydrate all links in this vector using a repository store.
    ///
    /// Fails if any link cannot be hydrated.
    fn hydrate_all_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Result<Vec<RelationalLink<'data, R, SourceD, TargetD, M>>, RelationalLinkError>
    where
        RD: RedbRepositoryDefinitions;
    
    /// Hydrate as many links as possible, keeping dehydrated versions for failures.
    fn hydrate_best_effort_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Vec<RelationalLink<'data, R, SourceD, TargetD, M>>
    where
        RD: RedbRepositoryDefinitions;
}

impl<'data, R, SourceD, TargetD, M> RepositoryHydrateVec<'data, R, SourceD, TargetD, M>
    for Vec<RelationalLink<'data, R, SourceD, TargetD, M>>
where
    R: NetabaseRepository,
    SourceD: NetabaseDefinition + InRepository<R> + 'static,
    SourceD::Discriminant: std::fmt::Debug,
    TargetD: RedbDefinition + InRepository<R> + Clone + 'static,
    TargetD::Discriminant: std::fmt::Debug + 'static,
    M: NetabaseModel<TargetD> + Clone,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Primary: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Relational: Clone + redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Blob: redb::Key + 'static,
    <M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription: 'static,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    for<'a> <M::Keys as NetabaseModelKeys<TargetD, M>>::Primary: std::borrow::Borrow<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Primary as redb::Value>::SelfType<'a>>,
    for<'a> <M::Keys as NetabaseModelKeys<TargetD, M>>::Blob: std::borrow::Borrow<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as redb::Value>::SelfType<'a>>,
    for<'a> <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem: std::borrow::Borrow<<<<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem as redb::Value>::SelfType<'a>>,
    <<M::Keys as NetabaseModelKeys<TargetD, M>>::Blob as crate::traits::registry::models::keys::blob::NetabaseModelBlobKey<TargetD, M>>::BlobItem: redb::Key + 'static,
    TargetD::SubscriptionKeys: redb::Key + 'static,
    for<'db> M: RedbNetbaseModel<'db, TargetD> + RedbModelCrud<'db, TargetD>,
    for<'db, 'a> <M as RedbNetbaseModel<'db, TargetD>>::TableV: redb::Value<SelfType<'a> = M>,
    RelationalLink<'data, R, SourceD, TargetD, M>: RepositoryHydrate<'data, R, SourceD, TargetD, M>,
{
    fn hydrate_all_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Result<Vec<RelationalLink<'data, R, SourceD, TargetD, M>>, RelationalLinkError>
    where
        RD: RedbRepositoryDefinitions,
    {
        self.into_iter()
            .map(|link| link.hydrate_from_repo(repo))
            .collect()
    }
    
    fn hydrate_best_effort_from_repo<RD>(
        self,
        repo: &RedbRepositoryStore<RD>,
    ) -> Vec<RelationalLink<'data, R, SourceD, TargetD, M>>
    where
        RD: RedbRepositoryDefinitions,
    {
        self.into_iter()
            .map(|link| {
                let pk = link.get_primary_key().clone();
                link.hydrate_from_repo(repo).unwrap_or_else(|_| RelationalLink::new_dehydrated(pk))
            })
            .collect()
    }
}
