//! Key trait definitions for models.
//!
//! This module provides the trait system for all key types used by models.
//! Keys are fundamental to how models are stored, indexed, and queried in Netabase.
//!
//! # Key Types
//!
//! Each model has multiple key types for different purposes:
//!
//! ## Primary Keys ([`primary`])
//! - Unique identifier for each model instance
//! - Required for all models
//! - Used for direct lookups and updates
//!
//! ## Secondary Keys ([`secondary`])
//! - Additional indexed fields for fast queries
//! - Optional, can have multiple per model
//! - Example: Email address on a User model
//!
//! ## Relational Keys ([`relational`])
//! - Type-safe foreign key references to other models
//! - Optional, enforces repository boundaries
//! - Example: `author_id` linking Post to User
//!
//! ## Blob Keys ([`blob`])
//! - Keys for large binary data chunks
//! - Auto-generated for fields marked with `#[blob]`
//! - Handles data > 60KB via chunking
//!
//! ## Subscription Keys ([`subscription`])
//! - Topic-based pub/sub membership
//! - Optional, for P2P synchronization
//! - Example: User subscribing to a hashtag
//!
//! ## Libp2p Keys ([`libp2p`])
//! - P2P provider advertisement keys
//! - Used in distributed network discovery
//!
//! # The NetabaseModelKeys Trait
//!
//! The [`NetabaseModelKeys`] trait aggregates all key types for a model. It's
//! automatically implemented by the `#[derive(NetabaseModel)]` macro.
//!
//! # Example
//!
//! ```rust
//! // The macro generates a Keys type that implements NetabaseModelKeys:
//! #[derive(NetabaseModel)]
//! pub struct User {
//!     #[primary_key]
//!     pub id: UserId,           // -> Keys::Primary
//!     
//!     #[secondary_key]
//!     pub email: String,        // -> Keys::Secondary (Email variant)
//!     
//!     #[link(MyDef, Company)]
//!     pub company: CompanyId,   // -> Keys::Relational (Company variant)
//! }
//! ```

use crate::traits::registry::models::keys::blob::NetabaseModelBlobKey;
use crate::traits::registry::models::keys::libp2p::NetabaseModelLibp2pProviderKey;
pub use crate::traits::registry::models::keys::primary::NetabaseModelPrimaryKey;
pub use crate::traits::registry::models::keys::relational::{
    NetabaseModelRelationalKey, NetabaseModelRelationalKeyForeign,
};
pub use crate::traits::registry::models::keys::secondary::NetabaseModelSecondaryKey;
pub use crate::traits::registry::models::keys::subscription::NetabaseModelSubscriptionKey;
use crate::traits::registry::{definition::NetabaseDefinition, models::model::{NetabaseModel, NetabaseModelMarker}};
use std::ops::{Bound, RangeBounds};

pub mod blob;
pub mod libp2p;
pub mod primary;
pub mod relational;
pub mod secondary;
pub mod subscription;

/// Trait that aggregates all key types for a model.
///
/// This trait is automatically implemented by the `#[derive(NetabaseModel)]` macro.
/// It defines the six key types that a model can have, each serving a different
/// purpose in the storage and query system.
///
/// # Type Parameters
///
/// - `D`: The definition this model belongs to
/// - `M`: The model type itself
///
/// # Associated Types
///
/// Each associated type implements its corresponding key trait for model semantics.
/// The `redb::Key` bounds are currently required for the redb backend.
///
/// - `Primary`: The primary key type (required, non-empty)
/// - `Secondary`: Secondary index keys (enum of possible indexes)
/// - `Relational`: Foreign key references (enum of link fields)
/// - `Subscription`: Pub/sub topic keys (enum of subscriptions)
/// - `Blob`: Large data chunk keys (enum of blob fields)
/// - `Libp2p`: P2P provider keys (for network discovery)
///
/// # Backend-Specific Bounds
///
/// This core trait is backend-agnostic and does **not** require any particular
/// database key traits. Backend-specific crates (like the redb backend) add
/// their own bounds on top via traits such as
/// [`RedbNetbaseModel`](crate::traits::registry::models::model::redb_model::RedbNetbaseModel)
/// and helper bounds in `databases::redb`.
///
/// # Example
///
/// ```rust
/// // Generated by the NetabaseModel macro:
/// impl NetabaseModelKeys<MyDef, User> for UserKeys {
///     type Primary = UserId;
///     type Secondary = UserSecondaryKey;  // enum { Email, Phone, ... }
///     type Relational = UserRelationalKey; // enum { Company, Manager, ... }
///     type Subscription = UserSubscriptionKey;
///     type Blob = UserBlobKey;
///     type Libp2p = UserLibp2pKey;
/// }
/// ```
///
/// # Future Direction
///
/// The `redb::Key` bounds on this trait are planned to be moved to
/// backend-specific extension traits to enable true backend-agnosticism.
/// Use `RedbCompatibleKeys` for new code that wants this separation.
pub trait NetabaseModelKeys<
    D: NetabaseDefinition,
    M: NetabaseModelMarker<D>,
    B = crate::traits::registry::backend::RedbBackend,
>: std::marker::Sized where
    D::Discriminant: 'static + std::fmt::Debug,
{
    /// Primary key type - uniquely identifies model instances.
    type Primary: NetabaseModelPrimaryKey<D, M>;
    /// Secondary key type - enum of all secondary indexed fields.
    type Secondary: NetabaseModelSecondaryKey<D, M>;
    /// Relational key type - enum of all foreign key fields.
    type Relational: NetabaseModelRelationalKey<D, M>;
    /// Subscription key type - enum of all pub/sub topics.
    type Subscription: NetabaseModelSubscriptionKey<D, M> + 'static;
    /// Blob key type - enum of all large data fields.
    type Blob: NetabaseModelBlobKey<D, M>;
    /// Libp2p key type - for P2P provider advertisement.
    type Libp2p: NetabaseModelLibp2pProviderKey<D, M>;
}

/// Trait for extracting the inner value from a key wrapper type.
///
/// Many key types wrap an inner value (e.g., `UserId(String)`). This trait
/// provides a uniform interface for accessing the wrapped value.
pub trait NetabaseKeyWrapper {
    /// The inner type being wrapped.
    type Inner: ?Sized;

    /// Get a reference to the inner value.
    fn as_inner(&self) -> &Self::Inner;

    /// Consume self and return the inner value.
    fn into_inner(self) -> Self::Inner;
}

/// Basic range over a single key type.
///
/// This mirrors the semantics of `Table::range` for `start..end` style ranges
/// and is reused across primary/secondary/blob/relational key spaces.
#[derive(Clone)]
pub enum SimpleKeyRange<K> {
    /// Equivalent to `..` (full range over all keys).
    All,
    /// Equivalent to `start..` (inclusive start, unbounded end).
    From { start: K },
    /// Equivalent to `..end` or `..=end` depending on `inclusive`.
    To { end: K, inclusive: bool },
    /// Equivalent to `start..end` / `start..=end` with explicit inclusivity.
    Between {
        start: K,
        end: K,
        start_inclusive: bool,
        end_inclusive: bool,
    },
}

impl<K> RangeBounds<K> for SimpleKeyRange<K> {
    fn start_bound(&self) -> Bound<&K> {
        match self {
            SimpleKeyRange::All | SimpleKeyRange::To { .. } => Bound::Unbounded,
            SimpleKeyRange::From { start } => Bound::Included(start),
            SimpleKeyRange::Between {
                start,
                start_inclusive,
                ..
            } => {
                if *start_inclusive {
                    Bound::Included(start)
                } else {
                    Bound::Excluded(start)
                }
            }
        }
    }

    fn end_bound(&self) -> Bound<&K> {
        match self {
            SimpleKeyRange::All | SimpleKeyRange::From { .. } => Bound::Unbounded,
            SimpleKeyRange::To { end, inclusive } => {
                if *inclusive {
                    Bound::Included(end)
                } else {
                    Bound::Excluded(end)
                }
            }
            SimpleKeyRange::Between {
                end,
                end_inclusive,
                ..
            } => {
                if *end_inclusive {
                    Bound::Included(end)
                } else {
                    Bound::Excluded(end)
                }
            }
        }
    }
}


/// Model-level range expression across primary and secondary key spaces.
///
/// This struct is built using a builder-style API, allowing you to
/// specify intersecting ranges across the primary and secondary
/// key spaces for a given model.
pub struct ModelKeyRange<D, M>
where
    D: NetabaseDefinition,
    D::Discriminant: 'static + std::fmt::Debug,
    M: NetabaseModel<D>,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    /// Optional range over the main primary-key table.
    pub primary: Option<SimpleKeyRange<<M::Keys as NetabaseModelKeys<D, M>>::Primary>>,
    /// Ranges over secondary index tables (interpreted by higher-level code).
    pub secondary: Vec<SimpleKeyRange<<M::Keys as NetabaseModelKeys<D, M>>::Secondary>>,
}

impl<D, M> ModelKeyRange<D, M>
where
    D: NetabaseDefinition,
    D::Discriminant: 'static + std::fmt::Debug,
    M: NetabaseModel<D>,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    /// Create an empty range (no constraints).
    pub fn new() -> Self {
        Self {
            primary: None,
            secondary: Vec::new(),
        }
    }

    /// Set or replace the primary-key range.
    pub fn with_primary(range: SimpleKeyRange<<M::Keys as NetabaseModelKeys<D, M>>::Primary>) -> Self {
        Self {
            primary: Some(range),
            secondary: Vec::new(),
        }
    }

    /// Add or replace the primary-key range on an existing builder.
    pub fn and_primary(mut self, range: SimpleKeyRange<<M::Keys as NetabaseModelKeys<D, M>>::Primary>) -> Self {
        self.primary = Some(range);
        self
    }

    /// Add an intersecting secondary-key range.
    pub fn and_secondary(mut self, range: SimpleKeyRange<<M::Keys as NetabaseModelKeys<D, M>>::Secondary>) -> Self {
        self.secondary.push(range);
        self
    }

}

impl<D, M> RangeBounds<<M::Keys as NetabaseModelKeys<D, M>>::Primary> for ModelKeyRange<D, M>
where
    D: NetabaseDefinition,
    D::Discriminant: 'static + std::fmt::Debug,
    M: NetabaseModel<D>,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Secondary as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Relational as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Blob as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Subscription as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
    <<<M as NetabaseModel<D>>::Keys as NetabaseModelKeys<D, M>>::Libp2p as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    fn start_bound(&self) -> Bound<&<M::Keys as NetabaseModelKeys<D, M>>::Primary> {
        match &self.primary {
            Some(range) => range.start_bound(),
            None => Bound::Unbounded,
        }
    }

    fn end_bound(&self) -> Bound<&<M::Keys as NetabaseModelKeys<D, M>>::Primary> {
        match &self.primary {
            Some(range) => range.end_bound(),
            None => Bound::Unbounded,
        }
    }
}


