//! Secondary key trait for alternative lookups.
//!
//! Secondary keys provide alternative ways to look up models besides the primary key.
//! Each secondary key index maps secondary key values → primary keys.
//!
//! # Use Cases
//!
//! - Looking up users by email address
//! - Finding posts by slug
//! - Querying products by SKU
//! - Any field you want to search/filter by
//!
//! # Examples
//!
//! ```rust
//! #[derive(NetabaseModel)]
//! pub struct User {
//!     #[primary_key]
//!     pub id: String,
//!     
//!     #[secondary_key]  // Indexed - can look up user by email
//!     pub email: String,
//!     
//!     pub name: String,   // Not indexed, can't search by this
//! }
//! ```
//!
//! See [`doc_example`](crate::doc_example) for working examples.
//!
//! # Performance
//!
//! - Secondary indexes enable fast lookups: O(log n)
//! - Each secondary index requires additional storage
//! - Updates to secondary fields require index updates
//! - Consider trade-offs: query speed vs. write speed and storage
//!
//! # Rules
//!
//! 1. Secondary keys don't need to be unique (multiple records can have same value)
//! 2. Secondary keys should be stable and deterministic
//! 3. Avoid indexing frequently-changing fields
//! 4. Keep secondary keys reasonably sized for index efficiency

use crate::traits::registry::definition::NetabaseDefinition;
use crate::traits::registry::models::StoreKeyMarker;
pub use crate::traits::registry::models::keys::primary::NetabaseModelPrimaryKey;
use crate::traits::registry::models::model::NetabaseModelMarker;

/// Marker trait for secondary key types.
///
/// Secondary keys provide alternative indexes for looking up models.
/// The associated `PrimaryKey` type indicates what this secondary key resolves to.
///
/// This is a simple marker trait without the K parameter to avoid
/// early/late-bound lifetime issues with GATs.
///
/// # Automatic Implementation
///
/// Generated by the `#[derive(NetabaseModel)]` macro for fields marked `#[secondary_key]`.
/// The macro generates an enum of all secondary keys for lookup.
///
/// See [`doc_example`](crate::doc_example) for pre-built examples.
pub trait NetabaseModelSecondaryKey<D: NetabaseDefinition, M: NetabaseModelMarker<D>>:
    StoreKeyMarker<D> + Clone
where
    D::Discriminant: 'static + std::fmt::Debug,
{
    type PrimaryKey: NetabaseModelPrimaryKey<D, M>;
}
