//! Repository-based boilerplate library demonstrating repository isolation.
//!
//! This module shows how definitions can be grouped into repositories,
//! with compile-time enforcement of data graph completeness.
//!
//! # Example Structure
//!
//! ```text
//! EmployeeRepo
//! ├── Employee (User, Shift)
//! └── Inventory (Product)
//!
//! ManagerRepo  
//! ├── Employee (User, Shift) - same definition, different context
//! └── Reports (Report)
//! ```

use serde::{Deserialize, Serialize};

// ============================================================================
// Employee Definition - belongs to both EmployeeRepo and ManagerRepo
// ============================================================================

#[netabase_macros::netabase_definition(Employee, repos(EmployeeRepo, ManagerRepo))]
pub mod employee {
    use super::*;

    /// A user/employee in the system
    #[derive(
        netabase_macros::NetabaseModel,
        Debug,
        Clone,
        Serialize,
        Deserialize,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
    )]
    pub struct User {
        #[primary_key]
        pub id: String,

        #[secondary_key]
        pub name: String,

        #[secondary_key]
        pub email: String,

        pub department: String,
    }

    /// A work shift
    #[derive(
        netabase_macros::NetabaseModel,
        Debug,
        Clone,
        Serialize,
        Deserialize,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
    )]
    pub struct Shift {
        #[primary_key]
        pub id: String,

        #[secondary_key]
        pub date: String,

        /// Links to the employee working this shift (same definition)
        #[link(Employee, User)]
        pub employee_id: String,

        pub hours: u8,
    }
}

// ============================================================================
// Inventory Definition - belongs only to EmployeeRepo
// ============================================================================

#[netabase_macros::netabase_definition(Inventory, repos(EmployeeRepo))]
pub mod inventory {
    use super::employee::{Employee, User, UserID};
    use super::*;

    /// A product in inventory
    #[derive(
        netabase_macros::NetabaseModel,
        Debug,
        Clone,
        Serialize,
        Deserialize,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
    )]
    pub struct Product {
        #[primary_key]
        pub sku: String,

        #[secondary_key]
        pub name: String,

        #[secondary_key]
        pub category: String,

        pub price_cents: u64,

        pub stock_count: u32,

        /// Links to the employee who last updated this product
        #[link(Employee, User)]
        pub last_updated_by: String,
    }
}

// ============================================================================
// Reports Definition - belongs only to ManagerRepo
// ============================================================================

#[netabase_macros::netabase_definition(Reports, repos(ManagerRepo))]
pub mod reports {
    use super::employee::{Employee, User, UserID};
    use super::*;

    /// A report generated by a manager
    #[derive(
        netabase_macros::NetabaseModel,
        Debug,
        Clone,
        Serialize,
        Deserialize,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
    )]
    pub struct Report {
        #[primary_key]
        pub id: String,

        #[secondary_key]
        pub title: String,

        #[secondary_key]
        pub report_date: String,

        /// Links to the manager who created this report
        #[link(Employee, User)]
        pub created_by: String,

        pub content: String,

        pub is_published: bool,
    }
}

// ============================================================================
// Repository Definitions
// ============================================================================

/// Employee repository - accessible by all employees
/// Contains: Employee (User, Shift), Inventory (Product)
#[netabase_macros::netabase_repository(EmployeeRepo)]
pub mod employee_repo {
    // The repository macro will automatically collect definitions
    // that have `repos(EmployeeRepo)` in their netabase_definition attribute
}

/// Manager repository - accessible only by managers  
/// Contains: Employee (User, Shift), Reports (Report)
#[netabase_macros::netabase_repository(ManagerRepo)]
pub mod manager_repo {
    // The repository macro will automatically collect definitions
    // that have `repos(ManagerRepo)` in their netabase_definition attribute
}

// ============================================================================
// Re-exports
// ============================================================================

pub use employee::*;
pub use inventory::*;
pub use reports::*;

// Re-export repository types
pub use employee_repo::*;
pub use manager_repo::*;
