//! Example demonstrating libp2p Kademlia DHT integration with NetabaseStore
//!
//! This example shows how to:
//! 1. Use the KademliaRecord and KademliaRecordKey traits with blanket implementations
//! 2. Convert between NetabaseDefinition and libp2p Records
//! 3. Implement a RecordStore using the provided helper functions
//! 4. Manage ProviderRecords with the helper utilities
//! 5. Test the blanket implementations work automatically for types that meet the trait bounds

use std::borrow::Cow;
use std::collections::HashMap;

// Only compile when libp2p feature is enabled
#[cfg(feature = "libp2p")]
use libp2p::{
    PeerId,
    kad::{
        ProviderRecord, Record, RecordKey,
        store::{Error as StoreError, RecordStore},
    },
};

use netabase_store::{
    error::EncodingDecodingError,
    traits::{
        definition::{NetabaseDefinition, NetabaseDefinitionDiscriminants, NetabaseDefinitionKeys},
        dht::{KademliaRecord, KademliaRecordKey, provider_record_helpers},
        model::{NetabaseModel, NetabaseModelKey},
        store::Store,
    },
};

use bincode::{Decode, Encode};
use strum::EnumIter;

// Example data structures
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct UserProfile {
    pub id: String,
    pub name: String,
    pub email: String,
    pub bio: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct BlogPost {
    pub id: String,
    pub title: String,
    pub content: String,
    pub author_id: String,
    pub created_at: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct UserProfileKey {
    pub id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct BlogPostKey {
    pub id: String,
}

// Example NetabaseDefinition enum (this would typically be generated by the macro)
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode, strum::EnumDiscriminants)]
#[strum_discriminants(derive(EnumIter, Encode, Decode, Hash))]
#[strum_discriminants(name(ExampleDiscriminants))]
pub enum ExampleDefinition {
    UserProfile(UserProfile),
    BlogPost(BlogPost),
}

#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum ExampleDefinitionKeys {
    UserProfile(UserProfileKey),
    BlogPost(BlogPostKey),
}

// Trait implementations
impl NetabaseDefinitionDiscriminants for ExampleDiscriminants {}
impl NetabaseDefinitionKeys for ExampleDefinitionKeys {
    type Discriminants = ExampleDiscriminants;

    fn discriminant(&self) -> Self::Discriminants {
        match self {
            ExampleDefinitionKeys::UserProfile(_) => ExampleDiscriminants::UserProfile,
            ExampleDefinitionKeys::BlogPost(_) => ExampleDiscriminants::BlogPost,
        }
    }
}

impl NetabaseDefinition for ExampleDefinition {
    type Keys = ExampleDefinitionKeys;
    type Discriminants = ExampleDiscriminants;

    fn keys(&self) -> Self::Keys {
        match self {
            ExampleDefinition::UserProfile(profile) => {
                ExampleDefinitionKeys::UserProfile(UserProfileKey {
                    id: profile.id.clone(),
                })
            }
            ExampleDefinition::BlogPost(post) => ExampleDefinitionKeys::BlogPost(BlogPostKey {
                id: post.id.clone(),
            }),
        }
    }
}

impl NetabaseModelKey for UserProfileKey {
    type Model = UserProfile;
}

impl NetabaseModelKey for BlogPostKey {
    type Model = BlogPost;
}

impl NetabaseModel for UserProfile {
    type Key = UserProfileKey;
    type Defined = ExampleDefinition;
    const DISCRIMINANT: ExampleDiscriminants = ExampleDiscriminants::UserProfile;

    fn key(&self) -> Self::Key {
        UserProfileKey {
            id: self.id.clone(),
        }
    }
}

impl NetabaseModel for BlogPost {
    type Key = BlogPostKey;
    type Defined = ExampleDefinition;
    const DISCRIMINANT: ExampleDiscriminants = ExampleDiscriminants::BlogPost;

    fn key(&self) -> Self::Key {
        BlogPostKey {
            id: self.id.clone(),
        }
    }
}

impl From<UserProfile> for ExampleDefinition {
    fn from(profile: UserProfile) -> Self {
        ExampleDefinition::UserProfile(profile)
    }
}

impl From<BlogPost> for ExampleDefinition {
    fn from(post: BlogPost) -> Self {
        ExampleDefinition::BlogPost(post)
    }
}

// Note: The DHT traits (KademliaRecord and KademliaRecordKey) are automatically
// implemented via blanket implementations for any type that satisfies the bounds:
// - NetabaseDefinition + bincode::Encode + bincode::Decode<()> for KademliaRecord
// - NetabaseDefinitionKeys + bincode::Encode + bincode::Decode<()> for KademliaRecordKey
//
// Since ExampleDefinition and ExampleDefinitionKeys already implement these traits,
// they automatically get the KademliaRecord and KademliaRecordKey implementations!

// Example RecordStore implementation
#[cfg(feature = "libp2p")]
pub struct ExampleRecordStore {
    // In-memory storage for demonstration
    records: HashMap<RecordKey, Record>,
    providers: sled::Tree, // Provider records stored in sled
    local_peer_id: PeerId,
}

#[cfg(feature = "libp2p")]
impl ExampleRecordStore {
    pub fn new(provider_db: sled::Db, local_peer_id: PeerId) -> Result<Self, sled::Error> {
        let providers =
            provider_record_helpers::create_provider_record_tree(&provider_db, "providers")?;

        Ok(Self {
            records: HashMap::new(),
            providers,
            local_peer_id,
        })
    }

    /// Store a NetabaseDefinition as a Record
    pub fn store_netabase_data(
        &mut self,
        data: ExampleDefinition,
    ) -> Result<(), EncodingDecodingError> {
        let record = data.try_to_record()?;
        self.put(record).map_err(|_| {
            EncodingDecodingError::Encoding(bincode::error::EncodeError::UnexpectedEnd)
        })?;
        Ok(())
    }

    /// Retrieve and deserialize NetabaseDefinition from a Record
    pub fn get_netabase_data(
        &self,
        key: &ExampleDefinitionKeys,
    ) -> Result<Option<ExampleDefinition>, EncodingDecodingError> {
        let record_key = key.try_to_record_key()?;

        if let Some(record) = self.get(&record_key) {
            let data = ExampleDefinition::try_from_record(record.into_owned())?;
            Ok(Some(data))
        } else {
            Ok(None)
        }
    }
}

#[cfg(feature = "libp2p")]
impl RecordStore for ExampleRecordStore {
    type RecordsIter<'a> = std::iter::Map<
        std::collections::hash_map::Values<'a, RecordKey, Record>,
        fn(&'a Record) -> Cow<'a, Record>,
    >;

    type ProvidedIter<'a> = std::iter::Map<
        provider_record_helpers::ProviderRecordIter<sled::Iter>,
        fn(std::borrow::Cow<'static, ProviderRecord>) -> std::borrow::Cow<'a, ProviderRecord>,
    >;

    fn get(&self, key: &RecordKey) -> Option<Cow<'_, Record>> {
        self.records.get(key).map(|record| Cow::Borrowed(record))
    }

    fn put(&mut self, record: Record) -> Result<(), StoreError> {
        // Check if record size is reasonable (basic validation)
        if record.value.len() > 1024 * 1024 {
            // 1MB limit
            return Err(StoreError::ValueTooLarge);
        }

        self.records.insert(record.key.clone(), record);
        Ok(())
    }

    fn remove(&mut self, key: &RecordKey) {
        self.records.remove(key);
    }

    fn records(&self) -> Self::RecordsIter<'_> {
        self.records.values().map(|record| Cow::Borrowed(record))
    }

    fn add_provider(&mut self, provider_record: ProviderRecord) -> Result<(), StoreError> {
        // Use helper function to add provider
        provider_record_helpers::add_provider_to_key(&self.providers, &provider_record)
            .map_err(|_| StoreError::ValueTooLarge)?;

        Ok(())
    }

    fn providers(&self, key: &RecordKey) -> Vec<ProviderRecord> {
        provider_record_helpers::get_providers_for_key(&self.providers, key)
            .unwrap_or_else(|_| Vec::new())
    }

    fn provided(&self) -> Self::ProvidedIter<'_> {
        // Filter for records where the provider is our local peer ID
        // For simplicity, we'll scan all provider records
        // In a real implementation, you might maintain a separate index
        provider_record_helpers::ProviderRecordIter::new(self.providers.iter()).map(|cow| match cow
        {
            std::borrow::Cow::Borrowed(record) => std::borrow::Cow::Borrowed(record),
            std::borrow::Cow::Owned(record) => std::borrow::Cow::Owned(record),
        })
    }

    fn remove_provider(&mut self, key: &RecordKey, peer: &PeerId) {
        // Use helper function to remove provider
        let _ = provider_record_helpers::remove_provider_from_key(&self.providers, key, peer);
    }
}

// Example usage
#[cfg(feature = "libp2p")]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Create example data
    let user_profile = UserProfile {
        id: "user123".to_string(),
        name: "Alice Smith".to_string(),
        email: "alice@example.com".to_string(),
        bio: Some("Software engineer passionate about distributed systems".to_string()),
    };

    let blog_post = BlogPost {
        id: "post456".to_string(),
        title: "Introduction to libp2p".to_string(),
        content: "libp2p is a modular network stack...".to_string(),
        author_id: "user123".to_string(),
        created_at: 1640995200, // Unix timestamp
    };

    // Convert to NetabaseDefinition
    let user_def = ExampleDefinition::UserProfile(user_profile.clone());
    let post_def = ExampleDefinition::BlogPost(blog_post.clone());

    // Demonstrate Record conversion using blanket implementations
    println!("=== Converting NetabaseDefinition to libp2p Records (Blanket Implementations) ===");

    let user_record = user_def.try_to_record()?;
    let post_record = post_def.try_to_record()?;

    println!("User record key: {:?}", user_record.key);
    println!("User record size: {} bytes", user_record.value.len());
    println!("Post record key: {:?}", post_record.key);
    println!("Post record size: {} bytes", post_record.value.len());

    // Demonstrate round-trip serialization
    println!("\n=== Round-trip Serialization Test ===");

    let recovered_user = ExampleDefinition::try_from_record(user_record.clone())?;
    let recovered_post = ExampleDefinition::try_from_record(post_record.clone())?;

    match recovered_user {
        ExampleDefinition::UserProfile(recovered) => {
            println!("✓ User profile recovered successfully: {}", recovered.name);
            assert_eq!(recovered, user_profile);
        }
        _ => panic!("Wrong type recovered"),
    }

    match recovered_post {
        ExampleDefinition::BlogPost(recovered) => {
            println!("✓ Blog post recovered successfully: {}", recovered.title);
            assert_eq!(recovered, blog_post);
        }
        _ => panic!("Wrong type recovered"),
    }

    // Demonstrate RecordStore usage
    println!("\n=== RecordStore Integration ===");

    let temp_db = sled::open("temp_provider_db")?;
    let local_peer = PeerId::random();
    let mut store = ExampleRecordStore::new(temp_db, local_peer)?;

    // Store data using the high-level interface
    store.store_netabase_data(user_def.clone())?;
    store.store_netabase_data(post_def.clone())?;

    // Retrieve data using keys
    let user_key = ExampleDefinitionKeys::UserProfile(UserProfileKey {
        id: "user123".to_string(),
    });

    if let Some(retrieved_user) = store.get_netabase_data(&user_key)? {
        println!("✓ Retrieved user from store: {:?}", retrieved_user.keys());
    }

    // Demonstrate ProviderRecord management
    println!("\n=== ProviderRecord Management ===");

    use libp2p::Multiaddr;

    let provider_record = ProviderRecord {
        key: user_record.key.clone(),
        provider: local_peer,
        expires: None,
        addresses: vec![
            "/ip4/127.0.0.1/tcp/12345".parse::<Multiaddr>()?,
            "/ip6/::1/tcp/12345".parse::<Multiaddr>()?,
        ],
    };

    store.add_provider(provider_record)?;

    let providers = store.providers(&user_record.key);
    println!("✓ Found {} providers for user record", providers.len());

    println!("\n=== Success! All DHT operations completed ===");

    // Cleanup
    std::fs::remove_dir_all("temp_provider_db").ok();

    Ok(())
}

#[cfg(not(feature = "libp2p"))]
fn main() {
    println!("This example requires the 'libp2p' feature to be enabled.");
    println!("Run with: cargo run --example dht_usage --features libp2p");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(feature = "libp2p")]
    fn test_record_conversion() {
        let user = UserProfile {
            id: "test_user".to_string(),
            name: "Test User".to_string(),
            email: "test@example.com".to_string(),
            bio: None,
        };

        let definition = ExampleDefinition::UserProfile(user.clone());

        // Convert to Record
        let record = definition.try_to_record().unwrap();

        // Convert back
        let recovered = ExampleDefinition::try_from_record(record).unwrap();

        // Verify
        assert_eq!(definition, recovered);
    }

    #[test]
    #[cfg(feature = "libp2p")]
    fn test_provider_record_helpers() {
        use libp2p::Multiaddr;

        let record_key = RecordKey::new(&b"test_key"[..]);
        let peer_id = PeerId::random();
        let addresses = vec!["/ip4/127.0.0.1/tcp/8080".parse::<Multiaddr>().unwrap()];

        let provider_record = ProviderRecord {
            key: record_key,
            provider: peer_id,
            expires: None,
            addresses,
        };

        // Test conversion to IVec format
        let (key_ivec, value_ivec) =
            provider_record_helpers::provider_record_to_ivec(&provider_record).unwrap();

        // Test conversion back
        let recovered =
            provider_record_helpers::ivec_to_provider_record(&key_ivec, &value_ivec).unwrap();

        assert_eq!(provider_record.key, recovered.key);
        assert_eq!(provider_record.provider, recovered.provider);
        assert_eq!(provider_record.addresses.len(), recovered.addresses.len());
    }

    #[test]
    #[cfg(feature = "libp2p")]
    fn test_blanket_implementations() {
        // Test that blanket implementations work automatically

        // Create test data
        let user = UserProfile {
            id: "blanket_test".to_string(),
            name: "Blanket Test".to_string(),
            email: "blanket@test.com".to_string(),
            bio: Some("Testing blanket implementations".to_string()),
        };

        let definition = ExampleDefinition::UserProfile(user);

        // These method calls work thanks to the blanket implementations
        // KademliaRecord trait methods:
        let keys = definition.record_keys(); // Calls the blanket implementation
        let serialized = definition.try_to_vec().unwrap();
        let record = definition.try_to_record().unwrap();

        // KademliaRecordKey trait methods:
        let key_serialized = keys.try_to_vec().unwrap();
        let record_key = keys.try_to_record_key().unwrap();

        // Verify round-trip
        let recovered_def = ExampleDefinition::try_from_record(record).unwrap();
        let recovered_keys = ExampleDefinitionKeys::try_from_record_key(&record_key).unwrap();

        // Verify they match
        assert_eq!(definition, recovered_def);
        // Note: We can't directly compare keys due to the enum structure,
        // but we can verify they serialize to the same bytes
        assert_eq!(key_serialized, recovered_keys.try_to_vec().unwrap());

        println!("✓ Blanket implementations working correctly!");
    }

    #[test]
    #[cfg(feature = "libp2p")]
    fn test_automatic_trait_availability() {
        // This test verifies that the traits are automatically available
        // without any manual implementation

        fn requires_kademlia_record<T: KademliaRecord>(_: &T) -> bool {
            true
        }
        fn requires_kademlia_record_key<T: KademliaRecordKey>(_: &T) -> bool {
            true
        }

        let definition = ExampleDefinition::UserProfile(UserProfile {
            id: "trait_test".to_string(),
            name: "Trait Test".to_string(),
            email: "trait@test.com".to_string(),
            bio: None,
        });

        let keys = definition.keys();

        // These calls succeed because of the blanket implementations
        assert!(requires_kademlia_record(&definition));
        assert!(requires_kademlia_record_key(&keys));

        println!("✓ Traits are automatically available via blanket implementations!");
    }
}
