//! Traits for managing relational links in netabase models
//!
//! This module defines the core traits for handling relationships between models
//! in a type-safe manner, following the same patterns as keys and discriminants.

use strum::IntoDiscriminant;

use crate::{
    MaybeSend, MaybeSync,
    definition::NetabaseDefinitionTrait,
    error::NetabaseError,
    traits::store_ops::{OpenTree, StoreOps},
};

/// Trait for models that have relational links to other models.
///
/// This trait provides **metadata-only access** to a model's relational structure.
/// It is **automatically derived** when a model contains `RelationalLink` fields.
/// You should never implement this trait manually - it's generated by the `#[derive(NetabaseModel)]` macro.
///
/// # Purpose
///
/// This trait serves two main purposes:
/// 1. **Type-level metadata**: Provides information about what relations a model has
/// 2. **Runtime introspection**: Allows querying which relation fields exist and their types
///
/// # Generated Types
///
/// For models with relational links, the derive macro automatically generates:
/// - `{ModelName}Relations` - Enum with a variant for each `RelationalLink` field
/// - Implementation of this trait with the Relations associated type
/// - Helper methods for each relation field (e.g., `author()`, `insert_author_if_entity()`)
///
/// # Relation Enum
///
/// The generated `{ModelName}Relations` enum provides:
/// ```ignore
/// pub enum PostRelations {
///     Author,    // For the `author` field
///     Category,  // For the `category` field
/// }
/// ```
///
/// This enum implements `NetabaseRelationDiscriminant` and provides:
/// - `field_name()` - Returns the field name as a string
/// - `target_model_name()` - Returns the target model type name
/// - `all_variants()` - Returns all possible relation fields
///
/// # Key Features
///
/// ## Metadata Access
/// ```ignore
/// // Check if a model has any relations
/// if post.has_relations() {
///     // Get all relation metadata
///     let relations = post.relations();
///     for (discriminant, relation) in relations {
///         println!("Field: {}", relation.field_name());
///         println!("Points to: {}", relation.target_model_name());
///     }
/// }
/// ```
///
/// ## Type Safety
/// ```ignore
/// // The Relations type is specific to each model
/// type PostRels = <Post as NetabaseRelationTrait<MyDef>>::Relations;
/// // PostRels is PostRelations enum
/// ```
///
/// # Generated Helper Methods
///
/// For each `RelationalLink` field, the macro generates:
///
/// ```ignore
/// impl Post {
///     // Get the link (read-only access)
///     pub fn author(&self) -> &RelationalLink<MyDef, User> { &self.author }
///
///     // Hydrate if it's a reference
///     pub fn author_hydrate<T>(&self, store: T) -> Result<Option<User>, NetabaseError>
///     where T: StoreOps<MyDef, User>
///     {
///         self.author.clone().hydrate(&store)
///     }
///
///     // Insert if it's an entity
///     pub fn insert_author_if_entity<S>(&self, store: &S) -> Result<(), NetabaseError>
///     where S: OpenTree<MyDef, User>
///     {
///         if let RelationalLink::Entity(entity) = &self.author {
///             let tree = store.open_tree();
///             tree.put_raw(entity.clone())
///         } else {
///             Ok(())
///         }
///     }
///
///     // Check if contains entity
///     pub fn author_is_entity(&self) -> bool {
///         self.author.is_entity()
///     }
///
///     // Get the key
///     pub fn author_key(&self) -> UserPrimaryKey {
///         self.author.key()
///     }
/// }
/// ```
///
/// # Examples
///
/// ## Basic Model Definition
///
/// ```ignore
/// use netabase_store::{netabase_definition_module, NetabaseModel, netabase};
/// use netabase_store::links::RelationalLink;
/// use netabase_store::traits::relation::NetabaseRelationTrait;
///
/// #[netabase_definition_module(MyDefinition, MyKeys)]
/// mod my_models {
///     use super::*;
///     use netabase_store::{NetabaseModel, netabase};
///
///     #[derive(NetabaseModel, Clone, Debug, PartialEq,
///              bincode::Encode, bincode::Decode,
///              serde::Serialize, serde::Deserialize)]
///     #[netabase(MyDefinition)]
///     pub struct Post {
///         #[primary_key]
///         pub id: u64,
///         pub title: String,
///
///         // Single relation
///         pub author: RelationalLink<MyDefinition, User>,
///
///         // Collection of relations
///         pub tags: Vec<RelationalLink<MyDefinition, Tag>>,
///     }
///
///     #[derive(NetabaseModel, Clone, Debug, PartialEq,
///              bincode::Encode, bincode::Decode,
///              serde::Serialize, serde::Deserialize)]
///     #[netabase(MyDefinition)]
///     pub struct User {
///         #[primary_key]
///         pub id: u64,
///         pub name: String,
///     }
///
///     #[derive(NetabaseModel, Clone, Debug, PartialEq,
///              bincode::Encode, bincode::Decode,
///              serde::Serialize, serde::Deserialize)]
///     #[netabase(MyDefinition)]
///     pub struct Tag {
///         #[primary_key]
///         pub id: u64,
///         pub name: String,
///     }
/// }
/// use my_models::*;
///
/// // Create instances
/// let user = User { id: 1, name: "Alice".into() };
/// let tag1 = Tag { id: 1, name: "Rust".into() };
/// let tag2 = Tag { id: 2, name: "Tutorial".into() };
///
/// let post = Post {
///     id: 1,
///     title: "Getting Started with Rust".into(),
///     author: RelationalLink::Entity(user),  // Eager load
///     tags: vec![
///         RelationalLink::Reference(tag1.primary_key()),  // Lazy load
///         RelationalLink::Reference(tag2.primary_key()),  // Lazy load
///     ],
/// };
///
/// // Check relations
/// assert!(post.has_relations());
/// let relations = post.relations();
/// assert_eq!(relations.len(), 2);  // author + tags
///
/// // Use generated helpers
/// if post.author_is_entity() {
///     println!("Author already loaded!");
/// }
/// ```
///
/// ## Introspection and Metadata
///
/// ```ignore
/// // Query relation metadata
/// for (disc, rel) in post.relations() {
///     match rel {
///         PostRelations::Author => {
///             println!("Author field points to: {}", rel.target_model_name());
///         }
///         PostRelations::Tags => {
///             println!("Tags field points to: {}", rel.target_model_name());
///         }
///     }
/// }
/// ```
///
/// # See Also
///
/// - [`RelationalLink`](crate::links::RelationalLink) - The link type itself
/// - [`NetabaseRelationDiscriminant`] - Trait for relation enum variants
/// - [`MultiModelStore`] - Trait for stores handling multiple model types
///
pub trait NetabaseRelationTrait<D: NetabaseDefinitionTrait>:
    crate::traits::model::NetabaseModelTrait<D>
    + bincode::Encode
    + bincode::Decode<()>
    + Sized
    + Clone
    + MaybeSend
    + MaybeSync
    + 'static
where
    <D as IntoDiscriminant>::Discriminant: crate::traits::definition::NetabaseDiscriminant,
{
    /// The relations enum that describes all relational fields in this model
    type Relations: NetabaseRelationDiscriminant
        + bincode::Encode
        + bincode::Decode<()>
        + Clone
        + IntoDiscriminant;

    /// Get all relations in this model as a HashMap keyed by discriminant
    ///
    /// This allows direct access to specific relation fields without iteration.
    fn relations(
        &self,
    ) -> std::collections::HashMap<
        <Self::Relations as IntoDiscriminant>::Discriminant,
        Self::Relations,
    >;

    /// Check if this model has any relational links
    fn has_relations(&self) -> bool {
        !self.relations().is_empty()
    }

    /// Insert relations recursively up to the specified depth
    ///
    /// This method inserts all relational entities in this model recursively,
    /// respecting the recursion level to control depth of insertion.
    ///
    /// # Arguments
    ///
    /// * `store` - The store to insert entities into
    /// * `level` - The recursion level controlling how deep to insert
    ///
    /// # Examples
    ///
    /// ```ignore
    /// // Insert with full recursion
    /// model.insert_relations_recursive(&store, RecursionLevel::Full)?;
    ///
    /// // Insert with limited depth
    /// model.insert_relations_recursive(&store, RecursionLevel::Value(2))?;
    ///
    /// // Don't recurse (equivalent to insert_relations_only)
    /// model.insert_relations_recursive(&store, RecursionLevel::None)?;
    /// ```
    fn insert_relations_recursive<S>(
        &self,
        store: &S,
        level: crate::links::RecursionLevel,
    ) -> Result<(), crate::error::NetabaseError>
    where
        S: MultiModelStore<D>,
        Self: crate::links::HasCustomRelationInsertion<D>;

    /// Insert relations recursively with depth tracking
    ///
    /// This method is similar to `insert_relations_recursive` but provides
    /// explicit depth tracking for the recursion level.
    ///
    /// # Arguments
    ///
    /// * `store` - The store to insert entities into
    /// * `level` - The recursion level controlling how deep to insert
    /// * `current_depth` - The current recursion depth for tracking
    ///
    /// # Examples
    ///
    /// ```ignore
    /// // Insert starting at depth 0
    /// model.insert_relations_recursive_with_depth(&store, RecursionLevel::Value(3), 0)?;
    /// ```
    fn insert_relations_recursive_with_depth<S>(
        &self,
        store: &S,
        level: crate::links::RecursionLevel,
        current_depth: u8,
    ) -> Result<(), crate::error::NetabaseError>
    where
        S: MultiModelStore<D>,
        Self: crate::links::HasCustomRelationInsertion<D>;
}

/// Trait for relation discriminants that provide metadata about relation fields
pub trait NetabaseRelationDiscriminant:
    IntoDiscriminant + Clone + std::fmt::Debug + MaybeSend + MaybeSync + 'static
{
    /// Get the field name for this relation discriminant
    fn field_name(&self) -> &'static str;

    /// Get the target model type name for this relation discriminant
    fn target_model_name(&self) -> &'static str;

    /// Get all possible relation discriminants for this type
    fn all_variants() -> Vec<Self>;
}

/// A type-safe relational link that uses the model's relation discriminant
///
/// This replaces the generic `RelationalLink<D, M>` with a more specific
/// approach that uses the model's generated relation enum.
#[derive(Clone, Debug, PartialEq)]
pub enum RelationLink<D, M, R>
where
    D: NetabaseDefinitionTrait,
    M: crate::traits::model::NetabaseModelTrait<D>,
    R: NetabaseRelationDiscriminant,
{
    /// A reference to an entity via its primary key
    Reference(M::PrimaryKey),
    /// A full entity instance
    Entity(M),
    /// Metadata about which relation field this link represents
    _RelationMarker(std::marker::PhantomData<R>),
}

impl<D, M, R> From<M> for RelationLink<D, M, R>
where
    D: NetabaseDefinitionTrait,
    M: crate::traits::model::NetabaseModelTrait<D>,
    R: NetabaseRelationDiscriminant,
{
    fn from(value: M) -> Self {
        RelationLink::Entity(value)
    }
}

impl<D, M, R> RelationLink<D, M, R>
where
    D: NetabaseDefinitionTrait,
    M: crate::traits::model::NetabaseModelTrait<D>,
    R: NetabaseRelationDiscriminant,
{
    /// Create a reference link from a primary key
    pub fn from_key(key: M::PrimaryKey) -> Self {
        RelationLink::Reference(key)
    }

    /// Create an entity link from a model instance
    pub fn from_entity(entity: M) -> Self {
        RelationLink::Entity(entity)
    }

    /// Hydrate this link, returning the entity if it's an Entity variant,
    /// or loading it from the store if it's a Reference variant
    pub fn hydrate<T: StoreOps<D, M>>(self, store: T) -> Result<Option<M>, NetabaseError> {
        match self {
            RelationLink::Reference(key) => store.get_raw(key),
            RelationLink::Entity(model) => Ok(Some(model)),
            RelationLink::_RelationMarker(_) => {
                unreachable!("RelationMarker should never be instantiated")
            }
        }
    }

    /// Get the primary key regardless of whether this is a Reference or Entity
    pub fn key(&self) -> M::PrimaryKey {
        match self {
            RelationLink::Reference(key) => key.clone(),
            RelationLink::Entity(entity) => entity.primary_key(),
            RelationLink::_RelationMarker(_) => {
                unreachable!("RelationMarker should never be instantiated")
            }
        }
    }

    /// Check if this link contains an Entity variant
    pub fn is_entity(&self) -> bool {
        matches!(self, RelationLink::Entity(_))
    }

    /// Check if this link contains a Reference variant
    pub fn is_reference(&self) -> bool {
        matches!(self, RelationLink::Reference(_))
    }

    /// Extract the entity if this is an Entity variant
    pub fn as_entity(&self) -> Option<&M> {
        match self {
            RelationLink::Entity(entity) => Some(entity),
            RelationLink::Reference(_) => None,
            RelationLink::_RelationMarker(_) => {
                unreachable!("RelationMarker should never be instantiated")
            }
        }
    }

    /// Extract the reference key if this is a Reference variant
    pub fn as_reference(&self) -> Option<&M::PrimaryKey> {
        match self {
            RelationLink::Reference(key) => Some(key),
            RelationLink::Entity(_) => None,
            RelationLink::_RelationMarker(_) => {
                unreachable!("RelationMarker should never be instantiated")
            }
        }
    }
}

/// Trait for stores that can handle insertion of multiple model types
///
/// This trait abstracts over the complexity of inserting models that may
/// have relational links to different model types.
pub trait MultiModelStore<D: NetabaseDefinitionTrait> {
    /// Insert a model with type-erased operations
    ///
    /// This method handles the complexity of determining which tree to use
    /// for a given model type and inserting it appropriately.
    fn insert_model_erased<M>(&self, model: &M) -> Result<(), NetabaseError>
    where
        M: crate::traits::model::NetabaseModelTrait<D> + Clone,
        Self: OpenTree<D, M>;

    /// Check if this store can handle a specific model type
    fn can_handle_model<M>(&self) -> bool
    where
        M: crate::traits::model::NetabaseModelTrait<D>;
}

/// Blanket implementation for any store that implements OpenTree
impl<D, S> MultiModelStore<D> for S
where
    D: NetabaseDefinitionTrait,
    S: ?Sized,
{
    fn insert_model_erased<M>(&self, model: &M) -> Result<(), NetabaseError>
    where
        M: crate::traits::model::NetabaseModelTrait<D> + Clone,
        Self: OpenTree<D, M>,
    {
        let tree = self.open_tree();
        tree.put_raw(model.clone())
    }

    fn can_handle_model<M>(&self) -> bool
    where
        M: crate::traits::model::NetabaseModelTrait<D>,
    {
        // In a real implementation, this would check if the store
        // implements OpenTree<D, M> for the specific model type.
        // For now, we'll assume it can handle any model.
        true
    }
}

/// Helper functions for working with relation links
pub mod relation_utils {
    use super::*;

    /// Extract all entity variants from a collection of relation links
    pub fn extract_entities<D, M, R, I>(links: I) -> Vec<M>
    where
        D: NetabaseDefinitionTrait,
        M: crate::traits::model::NetabaseModelTrait<D>,
        R: NetabaseRelationDiscriminant,
        I: IntoIterator<Item = RelationLink<D, M, R>>,
    {
        links
            .into_iter()
            .filter_map(|link| match link {
                RelationLink::Entity(entity) => Some(entity),
                _ => None,
            })
            .collect()
    }

    /// Extract all reference keys from a collection of relation links
    pub fn extract_references<D, M, R, I>(links: I) -> Vec<M::PrimaryKey>
    where
        D: NetabaseDefinitionTrait,
        M: crate::traits::model::NetabaseModelTrait<D>,
        R: NetabaseRelationDiscriminant,
        I: IntoIterator<Item = RelationLink<D, M, R>>,
    {
        links
            .into_iter()
            .filter_map(|link| match link {
                RelationLink::Reference(key) => Some(key),
                _ => None,
            })
            .collect()
    }

    /// Convert a collection of relation links to their primary keys
    pub fn to_keys<D, M, R, I>(links: I) -> Vec<M::PrimaryKey>
    where
        D: NetabaseDefinitionTrait,
        M: crate::traits::model::NetabaseModelTrait<D>,
        R: NetabaseRelationDiscriminant,
        I: IntoIterator<Item = RelationLink<D, M, R>>,
    {
        links.into_iter().map(|link| link.key()).collect()
    }
}

/// Re-export for backward compatibility during migration
pub use crate::links::RelationalLink as LegacyRelationalLink;
