//! Blob storage support for large data fields.
//!
//! This module provides types and traits for handling large binary data that needs
//! to be split into chunks for efficient storage and retrieval. Data larger than
//! 60KB is automatically chunked when stored.
//!
//! # Overview
//!
//! Blob fields in models are marked with the `#[netabase_blob_item]` attribute.
//! The macro generates implementations that handle:
//! - Automatic chunking of data > 60KB
//! - Serialization with postcard
//! - Reconstruction from chunks
//!
//! # Example
//!
//! Blob items are types that can be chunked for storage. They require the
//! `NetabaseBlobItem` derive macro and serde traits:
//!
//! ```rust,ignore
//! use netabase_macros::NetabaseBlobItem;
//! use serde::{Serialize, Deserialize};
//!
//! #[derive(NetabaseBlobItem, Serialize, Deserialize, Clone)]
//! pub struct LargeFile {
//!     pub data: Vec<u8>,
//!     pub metadata: String,
//! }
//! ```
//!
//! See [tests/blob_query_methods.rs](../tests/blob_query_methods.rs) for usage examples.

use serde::{Serialize, de::DeserializeOwned};

/// Link type for blob data, either complete or chunked.
///
/// This enum represents blob data in two states:
/// - `Complete`: The full blob item (used before storage)
/// - `Blobs`: A vec of blob chunks (used during storage/retrieval)
pub enum BlobLink<T: NetabaseBlobItem> {
    /// Complete blob item, not yet chunked
    Complete(T),
    /// Blob split into chunks for storage
    Blobs(Vec<T::Blobs>),
}

/// A wrapper for blob items stored in models.
/// 
/// This enum allows a model to hold either the full blob data (loaded/new)
/// or a reference key to the blob stored separately.
#[derive(Debug, Clone, Serialize, serde::Deserialize, PartialEq)]
pub enum BlobItem<T, K> {
    /// Full data of the blob item
    Full(T),
    /// Reference key to the stored blob
    Reference(K),
}

/// Trait for types that can be stored as blobs with automatic chunking.
///
/// Types implementing this trait can be automatically split into 60KB chunks
/// for storage and reconstructed on retrieval. The trait is typically derived
/// using the `#[netabase_blob_item]` macro.
///
/// # Chunk Size
///
/// Data is split into 60KB (60,000 byte) chunks to balance:
/// - Database page efficiency
/// - Memory usage during reads
/// - Parallel fetch granularity
///
/// # Serialization
///
/// Uses postcard for efficient binary serialization that's suitable for
/// network transmission in decentralized systems.
pub trait NetabaseBlobItem: Sized + Serialize + DeserializeOwned {
    /// The associated enum type for blob chunks.
    ///
    /// Generated by the macro, each variant represents a chunk.
    type Blobs;

    /// Split this item into blob chunks.
    ///
    /// Serializes the item (or its parts) and splits into 60KB chunks.
    /// Each chunk is wrapped in the appropriate enum variant.
    ///
    /// # Returns
    /// A vector of blob chunks.
    fn split_into_blobs(&self) -> Vec<Self::Blobs>;

    /// Reconstruct the original item from blob chunks.
    ///
    /// Takes a vector of blob chunks, sorts them by index (if applicable),
    /// concatenates the data, and deserializes back into the original item.
    ///
    /// # Arguments
    /// * `blobs` - Vector of blob chunks
    ///
    /// # Returns
    /// The reconstructed item
    fn reconstruct_from_blobs(blobs: Vec<Self::Blobs>) -> Self;

    /// Get the index of a blob chunk.
    ///
    /// Returns the index of this chunk if it represents a part of a split item.
    /// Returns None if the item is not chunked or if the index is not available.
    fn get_blob_index(&self) -> Option<u8> {
        None
    }
}