//! CLI client generation for database schemas.
//!
//! This module provides functionality to generate standalone CLI applications
//! for database schemas defined using the netabase_definition macro.

use crate::traits::registry::definition::{NetabaseDefinition, schema::DefinitionSchema};
use std::path::Path;
use std::fs;

/// Generate a CLI client application for a database definition.
///
/// This creates a complete Rust project with:
/// - Cargo.toml with necessary dependencies
/// - src/main.rs with CLI implementation using clap
/// - schema.toml with the database schema
/// - README.md with usage instructions
///
/// # Arguments
///
/// * `output_path` - Directory where the CLI client will be generated
///
/// # Returns
///
/// Returns `Ok(())` on success, or an IO error if generation fails.
pub fn generate_cli_client<D: NetabaseDefinition>(
    output_path: impl AsRef<Path>,
) -> std::io::Result<()>
where
    <D as strum::IntoDiscriminant>::Discriminant: 'static + std::fmt::Debug,
{
    let output_path = output_path.as_ref();
    let def_name = D::definition_name();
    let schema = D::schema();
    
    // Create output directory
    fs::create_dir_all(output_path)?;
    fs::create_dir_all(output_path.join("src"))?;
    
    // Generate Cargo.toml
    let cargo_toml = generate_cargo_toml(def_name);
    fs::write(output_path.join("Cargo.toml"), cargo_toml)?;
    
    // Generate schema.toml using export_toml (which includes full field information)
    let schema_toml = D::export_toml();
    fs::write(output_path.join("schema.toml"), schema_toml)?;
    
    // Generate main.rs
    let main_rs = generate_main_rs(def_name, &schema);
    fs::write(output_path.join("src/main.rs"), main_rs)?;
    
    // Generate README.md
    let readme = generate_readme(def_name, &schema);
    fs::write(output_path.join("README.md"), readme)?;
    
    Ok(())
}

fn generate_cargo_toml(def_name: &str) -> String {
    // Check if we're in development (test) mode - use path dependencies
    // Otherwise use published crates for production  
    let is_dev = std::env::var("NETABASE_CLI_DEV").is_ok();
    
    let dependencies = if is_dev {
        // Use relative paths for local development  
        // Assumes generated CLI is in netabase_store/test_generated_cli or similar
        r#"netabase_store = { path = "../" }
netabase_macros = { path = "../netabase_macros" }"#
    } else {
        // Use published crates for production
        r#"netabase_store = "0.1"
netabase_macros = "0.1""#
    };
    
    format!(
        r#"[package]
name = "{}_cli"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = {{ version = "4.5", features = ["derive"] }}
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
ron = "0.8"
toml = "0.8"
anyhow = "1.0"
redb = "3"
strum = {{ version = "0.27", features = ["derive"] }}
{}

[[bin]]
name = "client"
path = "src/main.rs"
"#,
        def_name.to_lowercase(),
        dependencies
    )
}

fn generate_schema_toml(schema: &DefinitionSchema) -> String {
    let mut output = String::new();
    
    // Top-level metadata (not in a [definition] section)
    output.push_str(&format!("schema_format_version = {}\n", schema.schema_format_version));
    output.push_str(&format!("name = \"{}\"\n", schema.name));
    
    // Subscriptions
    if !schema.subscriptions.is_empty() {
        output.push_str(&format!("subscriptions = {:?}\n", schema.subscriptions));
    } else {
        output.push_str("subscriptions = []\n");
    }
    output.push_str("\n");
    
    // Models with full field information
    for model in &schema.models {
        output.push_str(&format!("[[models]]\n"));
        output.push_str(&format!("name = \"{}\"\n", model.name));
        output.push_str(&format!("is_current = {}\n", model.is_current));
        output.push_str("is_libp2p_enabled = false\n");
        
        if let Some(family) = &model.family {
            output.push_str(&format!("family = \"{}\"\n", family));
        }
        if let Some(version) = model.version {
            output.push_str(&format!("version = {}\n", version));
        }
        
        // Note: We don't have field information in the schema, so we add a placeholder
        // The generated CLI will work with the types generated by infer_netabase_definition
        
        output.push_str("\n");
    }
    
    output
}

fn generate_main_rs(def_name: &str, schema: &DefinitionSchema) -> String {
    let mut output = String::new();
    
    // Imports
    output.push_str("use clap::{Parser, Subcommand};\n");
    output.push_str("use std::path::PathBuf;\n");
    output.push_str("use netabase_macros::infer_netabase_definition;\n");
    output.push_str("use netabase_store::prelude::*;\n\n");
    
    // Infer definition from schema.toml
    output.push_str("// Load database schema from schema.toml\n");
    output.push_str("infer_netabase_definition!(\"schema.toml\");\n");
    output.push_str(&format!("use {}Module::*;\n\n", def_name));
    
    // Main CLI struct
    output.push_str("#[derive(Parser)]\n");
    output.push_str(&format!("#[command(name = \"{}\")]\n", def_name.to_lowercase()));
    output.push_str("#[command(about = \"CLI client for database\", long_about = None)]\n");
    output.push_str("struct Cli {\n");
    output.push_str("    /// Path to the database\n");
    output.push_str("    #[arg(short, long, default_value = \"./database\")]\n");
    output.push_str("    database: PathBuf,\n\n");
    output.push_str("    #[command(subcommand)]\n");
    output.push_str("    command: Commands,\n");
    output.push_str("}\n\n");
    
    // Commands enum
    output.push_str("#[derive(Subcommand)]\n");
    output.push_str("enum Commands {\n");
    output.push_str("    /// Schema inspection commands\n");
    output.push_str("    Schema {\n");
    output.push_str("        #[command(subcommand)]\n");
    output.push_str("        command: SchemaCommands,\n");
    output.push_str("    },\n");
    
    // Add command for each model
    for model in &schema.models {
        if model.is_current {
            output.push_str(&format!("    /// {} operations\n", model.name));
            output.push_str(&format!("    {} {{\n", model.name));
            output.push_str("        #[command(subcommand)]\n");
            output.push_str(&format!("        command: {}Commands,\n", model.name));
            output.push_str("    },\n");
        }
    }
    
    output.push_str("}\n\n");
    
    // Schema commands
    output.push_str("#[derive(Subcommand)]\n");
    output.push_str("enum SchemaCommands {\n");
    output.push_str("    /// Display the schema\n");
    output.push_str("    Show,\n");
    output.push_str("    /// List all tables\n");
    output.push_str("    Tables,\n");
    output.push_str("}\n\n");
    
    // Model commands
    for model in &schema.models {
        if model.is_current {
            output.push_str(&format!("#[derive(Subcommand)]\n"));
            output.push_str(&format!("enum {}Commands {{\n", model.name));
            output.push_str("    /// Create a new record\n");
            output.push_str("    Create {\n");
            output.push_str("        /// JSON input\n");
            output.push_str("        #[arg(long, group = \"input\")]\n");
            output.push_str("        json: Option<String>,\n");
            output.push_str("        /// RON input\n");
            output.push_str("        #[arg(long, group = \"input\")]\n");
            output.push_str("        ron: Option<String>,\n");
            output.push_str("    },\n");
            output.push_str("    /// Read a record by ID\n");
            output.push_str("    Read {\n");
            output.push_str("        /// Record ID (JSON or RON format)\n");
            output.push_str("        id: String,\n");
            output.push_str("    },\n");
            output.push_str("    /// Update a record\n");
            output.push_str("    Update {\n");
            output.push_str("        /// JSON input\n");
            output.push_str("        #[arg(long, group = \"input\")]\n");
            output.push_str("        json: Option<String>,\n");
            output.push_str("        /// RON input\n");
            output.push_str("        #[arg(long, group = \"input\")]\n");
            output.push_str("        ron: Option<String>,\n");
            output.push_str("    },\n");
            output.push_str("    /// Delete a record\n");
            output.push_str("    Delete {\n");
            output.push_str("        /// Record ID (JSON or RON format)\n");
            output.push_str("        id: String,\n");
            output.push_str("    },\n");
            output.push_str("    /// List all records\n");
            output.push_str("    List {\n");
            output.push_str("        /// Maximum number of records to list\n");
            output.push_str("        #[arg(short, long)]\n");
            output.push_str("        limit: Option<usize>,\n");
            output.push_str("        /// Output format (json or ron)\n");
            output.push_str("        #[arg(short, long, default_value = \"json\")]\n");
            output.push_str("        format: String,\n");
            output.push_str("    },\n");
            output.push_str("    /// Count all records\n");
            output.push_str("    Count,\n");
            output.push_str("}\n\n");
        }
    }
    
    // Helper function to parse input
    output.push_str("/// Parse input from JSON or RON format\n");
    output.push_str("fn parse_input<T: serde::de::DeserializeOwned>(json: Option<String>, ron: Option<String>) -> anyhow::Result<T> {\n");
    output.push_str("    if let Some(json_str) = json {\n");
    output.push_str("        Ok(serde_json::from_str(&json_str)?)\n");
    output.push_str("    } else if let Some(ron_str) = ron {\n");
    output.push_str("        Ok(ron::from_str(&ron_str)?)\n");
    output.push_str("    } else {\n");
    output.push_str("        anyhow::bail!(\"Either --json or --ron must be provided\")\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    
    // Main function
    output.push_str("fn main() -> anyhow::Result<()> {\n");
    output.push_str("    let cli = Cli::parse();\n\n");
    
    // Open database
    output.push_str("    // Open or create the database\n");
    output.push_str("    let config = netabase_store::traits::store_config::StoreConfig {\n");
    output.push_str("        db_path: Some(cli.database.clone()),\n");
    output.push_str("        ..Default::default()\n");
    output.push_str("    };\n");
    output.push_str(&format!("    let store = RedbStore::<{}>::with_config(config)?;\n\n", def_name));
    
    output.push_str("    match cli.command {\n");
    output.push_str("        Commands::Schema { command } => {\n");
    output.push_str("            match command {\n");
    output.push_str("                SchemaCommands::Show => {\n");
    output.push_str(&format!("                    let schema = include_str!(\"../schema.toml\");\n"));
    output.push_str("                    println!(\"{}\", schema);\n");
    output.push_str("                }\n");
    output.push_str("                SchemaCommands::Tables => {\n");
    output.push_str("                    println!(\"Tables:\");\n");
    for model in &schema.models {
        if model.is_current {
            output.push_str(&format!("                    println!(\"  - {}\");\n", model.name));
        }
    }
    output.push_str("                }\n");
    output.push_str("            }\n");
    output.push_str("        }\n");
    
    // Implement model handlers
    for model in &schema.models {
        if model.is_current {
            output.push_str(&format!("        Commands::{} {{ command }} => {{\n", model.name));
            output.push_str(&format!("            match command {{\n"));
            
            // Create command
            output.push_str(&format!("                {}Commands::Create {{ json, ron }} => {{\n", model.name));
            output.push_str(&format!("                    let record: {} = parse_input(json, ron)?;\n", model.name));
            output.push_str("                    let txn = store.begin_write()?;\n");
            output.push_str("                    txn.create(&record)?;\n");
            output.push_str("                    txn.commit()?;\n");
            output.push_str("                    println!(\"Record created successfully\");\n");
            output.push_str("                }\n");
            
            // Read command
            output.push_str(&format!("                {}Commands::Read {{ id }} => {{\n", model.name));
            output.push_str(&format!("                    let key: {}ID = if id.starts_with('{{') {{\n", model.name));
            output.push_str("                        serde_json::from_str(&id)?\n");
            output.push_str("                    } else if id.starts_with('(') {\n");
            output.push_str("                        ron::from_str(&id)?\n");
            output.push_str("                    } else {\n");
            output.push_str("                        anyhow::bail!(\"ID must be in JSON or RON format\")\n");
            output.push_str("                    };\n");
            output.push_str("                    let txn = store.begin_read()?;\n");
            output.push_str(&format!("                    match txn.read::<{}>(&key)? {{\n", model.name));
            output.push_str("                        Some(record) => {\n");
            output.push_str("                            let json = serde_json::to_string_pretty(&record)?;\n");
            output.push_str("                            println!(\"{}\", json);\n");
            output.push_str("                        }\n");
            output.push_str("                        None => {\n");
            output.push_str("                            eprintln!(\"Record not found\");\n");
            output.push_str("                            std::process::exit(1);\n");
            output.push_str("                        }\n");
            output.push_str("                    }\n");
            output.push_str("                }\n");
            
            // Update command
            output.push_str(&format!("                {}Commands::Update {{ json, ron }} => {{\n", model.name));
            output.push_str(&format!("                    let record: {} = parse_input(json, ron)?;\n", model.name));
            output.push_str("                    let txn = store.begin_write()?;\n");
            output.push_str("                    txn.update(&record)?;\n");
            output.push_str("                    txn.commit()?;\n");
            output.push_str("                    println!(\"Record updated successfully\");\n");
            output.push_str("                }\n");
            
            // Delete command
            output.push_str(&format!("                {}Commands::Delete {{ id }} => {{\n", model.name));
            output.push_str(&format!("                    let key: {}ID = if id.starts_with('{{') {{\n", model.name));
            output.push_str("                        serde_json::from_str(&id)?\n");
            output.push_str("                    } else if id.starts_with('(') {\n");
            output.push_str("                        ron::from_str(&id)?\n");
            output.push_str("                    } else {\n");
            output.push_str("                        anyhow::bail!(\"ID must be in JSON or RON format\")\n");
            output.push_str("                    };\n");
            output.push_str("                    let txn = store.begin_write()?;\n");
            output.push_str(&format!("                    txn.delete::<{}>(&key)?;\n", model.name));
            output.push_str("                    txn.commit()?;\n");
            output.push_str("                    println!(\"Record deleted successfully\");\n");
            output.push_str("                }\n");
            
            // List command
            output.push_str(&format!("                {}Commands::List {{ limit, format }} => {{\n", model.name));
            output.push_str("                    let txn = store.begin_read()?;\n");
            output.push_str(&format!("                    let mut results: Vec<{}> = txn.list()?;\n", model.name));
            output.push_str("                    if let Some(max) = limit {\n");
            output.push_str("                        results.truncate(max);\n");
            output.push_str("                    }\n");
            output.push_str("                    match format.as_str() {\n");
            output.push_str("                        \"json\" => {\n");
            output.push_str("                            let json = serde_json::to_string_pretty(&results)?;\n");
            output.push_str("                            println!(\"{}\", json);\n");
            output.push_str("                        }\n");
            output.push_str("                        \"ron\" => {\n");
            output.push_str("                            let ron = ron::to_string(&results)?;\n");
            output.push_str("                            println!(\"{}\", ron);\n");
            output.push_str("                        }\n");
            output.push_str("                        _ => anyhow::bail!(\"Invalid format. Use 'json' or 'ron'\"),\n");
            output.push_str("                    }\n");
            output.push_str("                }\n");
            
            // Count command
            output.push_str(&format!("                {}Commands::Count => {{\n", model.name));
            output.push_str("                    let txn = store.begin_read()?;\n");
            output.push_str(&format!("                    let count = txn.count::<{}>()?;\n", model.name));
            output.push_str("                    println!(\"{}\", count);\n");
            output.push_str("                }\n");
            
            output.push_str("            }\n");
            output.push_str("        }\n");
        }
    }
    
    output.push_str("    }\n\n");
    output.push_str("    Ok(())\n");
    output.push_str("}\n");
    
    output
}

fn generate_readme(def_name: &str, schema: &DefinitionSchema) -> String {
    let mut output = String::new();
    
    output.push_str(&format!("# {} CLI Client\n\n", def_name));
    output.push_str("A command-line interface for interacting with the database.\n\n");
    
    output.push_str("## Building\n\n");
    output.push_str("```bash\n");
    output.push_str("cargo build --release\n");
    output.push_str("```\n\n");
    
    output.push_str("## Usage\n\n");
    output.push_str("```bash\n");
    output.push_str("# Display schema\n");
    output.push_str("./target/release/client --database ./mydb schema show\n\n");
    output.push_str("# List tables\n");
    output.push_str("./target/release/client --database ./mydb schema tables\n");
    
    for model in &schema.models {
        if model.is_current {
            output.push_str(&format!("\n# {} operations\n", model.name));
            output.push_str(&format!("./target/release/client --database ./mydb {} create --json '{{...}}'\n", model.name.to_lowercase()));
            output.push_str(&format!("./target/release/client --database ./mydb {} read <id>\n", model.name.to_lowercase()));
            output.push_str(&format!("./target/release/client --database ./mydb {} list\n", model.name.to_lowercase()));
        }
    }
    
    output.push_str("```\n");
    
    output
}
