//! # Netabase Store
//!
//! The core storage layer for Netabase, providing embedded database functionality
//! built on top of [sled](https://github.com/spacejam/sled). This crate handles
//! local data persistence, indexing, querying, and relational operations.
//!
//! ## Overview
//!
//! Netabase Store is the foundation layer that provides:
//! - Type-safe database operations through generated traits
//! - Primary and secondary key indexing
//! - Relational queries and foreign key support
//! - Advanced filtering and aggregation capabilities
//! - Batch operations for performance
//! - Optional libp2p integration for network serialization
//!
//! ## Architecture
//!
//! The crate is organized into several modules:
//!
//! - [`database`] - Core database types and implementations
//! - [`traits`] - Trait definitions for models, schemas, and operations
//! - [`errors`] - Error types and handling
//! - [`relational`] - Relational query support and foreign key handling
//!
//! ## Usage
//!
//! Most users will interact with this crate through the generated code from
//! `netabase_macros`, but direct usage is also supported:
//!
//! ```rust
//! use netabase_store::database::{NetabaseSledDatabase, NetabaseSledTree};
//! use netabase_store::traits::{NetabaseModel, NetabaseSecondaryKeyQuery};
//!
//! // Assuming you have a model type generated by macros
//! let db = NetabaseSledDatabase::<MySchema>::new_with_name("my_database")?;
//! let user_tree: NetabaseSledTree<User, UserKey> = db.get_main_tree()?;
//!
//! // Perform database operations
//! user_tree.insert(user.key(), user)?;
//! let retrieved = user_tree.get(user.key())?;
//! ```
//!
//! ## Features
//!
//! ### Core Features (always available)
//! - Local embedded database storage
//! - CRUD operations with type safety
//! - Primary and secondary key indexing
//! - Custom filtering and range queries
//! - Batch operations and transactions
//!
//! ### Optional Features
//! - `libp2p` - Enable network serialization support for distributed operations
//! - `record-store` - Additional record storage capabilities (requires libp2p)
//!
//! ## Performance Characteristics
//!
//! - **Primary Key Operations**: O(log n) where n is total records
//! - **Secondary Key Queries**: O(m) where m is matching records
//! - **Range Queries**: O(log n + m) for efficient prefix searches
//! - **Custom Filters**: O(n) - requires scanning all records
//! - **Batch Operations**: Significantly faster than individual operations
//!
//! ## Thread Safety
//!
//! All database operations are thread-safe. Multiple readers can access data
//! simultaneously, and writers are properly synchronized. However, the same
//! database path cannot be opened by multiple processes simultaneously due
//! to sled's single-writer constraint.
//!
//! ## Error Handling
//!
//! The crate uses comprehensive error types defined in the [`errors`] module.
//! All fallible operations return `Result` types with specific error information:
//!
//! ```rust
//! use netabase_store::errors::NetabaseStoreError;
//!
//! match user_tree.get(user_key) {
//!     Ok(Some(user)) => println!("Found: {:?}", user),
//!     Ok(None) => println!("User not found"),
//!     Err(NetabaseStoreError::Database(e)) => eprintln!("Database error: {}", e),
//!     Err(NetabaseStoreError::Serialization(e)) => eprintln!("Serialization error: {}", e),
//!     Err(e) => eprintln!("Other error: {}", e),
//! }
//! ```

pub mod database;
pub mod errors;
pub mod relational;

pub mod traits;
