//! Examples of code generated by Netabase macros.
//!
//! This module documents what code the macros generate by showing concrete examples.
//! Understanding the generated code helps debug issues and write better models.
//!
//! # `#[derive(NetabaseModel)]` - Generated Code
//!
//! ## Input
//!
//! ```rust
//! use netabase_macros::NetabaseModel;
//! use serde::{Serialize, Deserialize};
//!
//! #[derive(NetabaseModel, Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, PartialOrd, Ord)]
//! pub struct User {
//!     #[primary_key]
//!     pub id: String,
//!     
//!     #[secondary_key]
//!     pub email: String,
//!     
//!     pub name: String,
//! }
//! ```
//!
//! ## Generated Output (Conceptual)
//!
//! The macro generates approximately:
//!
//! ```rust
//! // 1. Primary key type alias
//! pub type UserID = String;
//!
//! // 2. Secondary key enum
//! #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, PartialOrd, Ord)]
//! pub enum UserSecondaryKeys {
//!     Email(String),
//! }
//!
//! // 3. Keys wrapper
//! pub struct UserKeys;
//!
//! impl NetabaseModelKeys<MyDef, User> for UserKeys {
//!     type Primary = UserID;
//!     type Secondary = UserSecondaryKeys;
//!     type Relational = (); // None in this example
//!     type Blob = (); // None in this example
//!     type Subscription = (); // None in this example
//! }
//!
//! // 4. Tree names for tables
//! #[derive(Debug, Clone)]
//! pub enum UserTreeNames {
//!     Primary,
//!     SecondaryEmail,
//! }
//!
//! // 5. NetabaseModel trait implementation
//! impl<D: NetabaseDefinition> NetabaseModel<D> for User
//! where
//!     Self: InModel<D>,
//! {
//!     type Keys = UserKeys;
//!     type TreeNames = UserTreeNames;
//!     
//!     fn extract_pk(&self) -> UserID {
//!         self.id.clone()
//!     }
//!     
//!     fn extract_secondary_keys(&self) -> Vec<UserSecondaryKeys> {
//!         vec![UserSecondaryKeys::Email(self.email.clone())]
//!     }
//!     
//!     // ... other methods
//! }
//!
//! // 6. Conversion implementations
//! impl From<User> for UserID {
//!     fn from(user: User) -> Self {
//!         user.id
//!     }
//! }
//!
//! impl From<&User> for UserID {
//!     fn from(user: &User) -> Self {
//!         user.id.clone()
//!     }
//! }
//! ```
//!
//! # `#[netabase_definition(Name)]` - Generated Code
//!
//! ## Input
//!
//! ```rust
//! #[netabase_definition(MyApp)]
//! mod my_app {
//!     #[derive(NetabaseModel)]
//!     pub struct User {
//!         #[primary_key]
//!         pub id: String,
//!     }
//!     
//!     #[derive(NetabaseModel)]
//!     pub struct Post {
//!         #[primary_key]
//!         pub id: String,
//!         
//!         #[link(MyApp, User)]
//!         pub author: String,
//!     }
//! }
//! ```
//!
//! ## Generated Output (Conceptual)
//!
//! ```rust
//! // 1. Definition enum wrapping all models
//! #[derive(Debug, Clone, strum::EnumDiscriminants)]
//! pub enum MyApp {
//!     User(User),
//!     Post(Post),
//! }
//!
//! // 2. Discriminant for pattern matching
//! #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
//! pub enum MyAppDiscriminant {
//!     User,
//!     Post,
//! }
//!
//! // 3. Tree names enum
//! #[derive(Debug, Clone)]
//! pub enum MyAppTreeNames {
//!     User(UserTreeNames),
//!     Post(PostTreeNames),
//! }
//!
//! // 4. Unified keys enum
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub enum MyAppKeys {
//!     UserPrimary(UserID),
//!     UserSecondary(UserSecondaryKeys),
//!     PostPrimary(PostID),
//!     PostSecondary(PostSecondaryKeys),
//!     PostRelational(PostRelationalKeys),
//! }
//!
//! // 5. NetabaseDefinition trait implementation
//! impl NetabaseDefinition for MyApp {
//!     type TreeNames = MyAppTreeNames;
//!     type DefKeys = MyAppKeys;
//!     type DebugName = &'static str;
//!     
//!     fn debug_name() -> Self::DebugName {
//!         "MyApp"
//!     }
//!     
//!     fn schema() -> DefinitionSchema {
//!         // Generated schema export code
//!         // ...
//!     }
//!     
//!     // ... other methods
//! }
//!
//! // 6. InModel trait implementations for compile-time checks
//! impl InModel<MyApp> for User {}
//! impl InModel<MyApp> for Post {}
//! ```
//!
//! # Relational Links - Generated Code
//!
//! When you use `#[link(Def, Model)]`:
//!
//! ```rust
//! #[derive(NetabaseModel)]
//! pub struct Post {
//!     #[primary_key]
//!     pub id: String,
//!     
//!     #[link(MyApp, User)]
//!     pub author_id: String,
//! }
//! ```
//!
//! The macro generates:
//!
//! ```rust
//! // 1. Relational key enum
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub enum PostRelationalKeys {
//!     AuthorId(RelationalLink<Standalone, MyApp, MyApp, User>),
//! }
//!
//! // 2. Key extraction in NetabaseModel impl
//! impl NetabaseModel<MyApp> for Post {
//!     // ...
//!     
//!     fn extract_relational_keys(&self) -> Vec<PostRelationalKeys> {
//!         vec![
//!             PostRelationalKeys::AuthorId(
//!                 RelationalLink::new(self.author_id.clone())
//!             )
//!         ]
//!     }
//! }
//! ```
//!
//! # Blob Fields - Generated Code
//!
//! When you use `#[blob]`:
//!
//! ```rust
//! #[derive(NetabaseModel)]
//! pub struct Document {
//!     #[primary_key]
//!     pub id: String,
//!     
//!     #[blob]
//!     pub content: Vec<u8>,
//! }
//! ```
//!
//! The macro generates:
//!
//! ```rust
//! // 1. Blob key enum
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub enum DocumentBlobKeys {
//!     Content,
//! }
//!
//! // 2. Blob extraction methods
//! impl NetabaseModel<MyApp> for Document {
//!     // ...
//!     
//!     fn extract_blobs(&self) -> Vec<(DocumentBlobKeys, Vec<u8>)> {
//!         vec![
//!             (DocumentBlobKeys::Content, self.content.clone())
//!         ]
//!     }
//! }
//! ```
//!
//! # Migration Version - Generated Code
//!
//! When you use `#[netabase_version]`:
//!
//! ```rust
//! #[derive(NetabaseModel)]
//! #[netabase_version(family = "User", version = 2)]
//! pub struct UserV2 {
//!     #[primary_key]
//!     pub id: String,
//!     pub email: String,
//!     pub phone: String, // New field
//! }
//! ```
//!
//! The macro generates:
//!
//! ```rust
//! impl VersionInfo for UserV2 {
//!     fn family() -> &'static str {
//!         "User"
//!     }
//!     
//!     fn version() -> u32 {
//!         2
//!     }
//! }
//!
//! // Migration chain registration
//! // Links UserV1 -> UserV2 in the migration graph
//! ```
//!
//! # Subscription Topics - Generated Code
//!
//! When models subscribe to topics:
//!
//! ```rust
//! // In definition
//! #[netabase_definition(MyApp, subscriptions(NewUser))]
//! mod my_app {
//!     #[derive(NetabaseModel)]
//!     #[subscribe(NewUser)]
//!     pub struct Notification {
//!         #[primary_key]
//!         pub id: String,
//!     }
//! }
//! ```
//!
//! The macro generates:
//!
//! ```rust
//! // 1. Subscription keys enum at definition level
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub enum MyAppSubscriptionKeys {
//!     NewUser(UserID), // Key of the topic publisher
//! }
//!
//! // 2. Subscription table for Notification
//! pub enum NotificationSubscriptionKeys {
//!     NewUser,
//! }
//!
//! // 3. Registry mapping topics to subscribers
//! const SUBSCRIPTION_REGISTRY: DefinitionSubscriptionRegistry<'static, MyApp> =
//!     DefinitionSubscriptionRegistry::new(&[
//!         SubscriptionEntry {
//!             topic: "NewUser",
//!             subscribers: &[MyAppDiscriminant::Notification],
//!         }
//!     ]);
//! ```
//!
//! # Helper Methods Generated
//!
//! The macros also generate helper methods:
//!
//! ```rust
//! // On each model:
//! impl User {
//!     /// Create from primary key and full data
//!     pub fn from_pk_and_data(pk: UserID, data: Self) -> Self {
//!         data
//!     }
//!     
//!     /// Get the primary key
//!     pub fn pk(&self) -> UserID {
//!         self.id.clone()
//!     }
//! }
//!
//! // On the definition:
//! impl MyApp {
//!     /// Export schema to TOML string
//!     pub fn export_toml() -> String {
//!         // ...
//!     }
//!     
//!     /// Get schema structure
//!     pub fn schema() -> DefinitionSchema {
//!         // ...
//!     }
//! }
//! ```
//!
//! # How to View Generated Code
//!
//! To see the actual generated code for your models:
//!
//! ```bash
//! # Use cargo-expand
//! cargo install cargo-expand
//! cargo expand --lib my_module
//!
//! # Or check the generated documentation
//! cargo doc --open
//! ```
//!
//! # Debugging Tips
//!
//! If macro expansion fails:
//!
//! 1. **Check Primary Key**: Every model needs exactly one `#[primary_key]`
//! 2. **Check Derives**: Models need `Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord`
//! 3. **Check Link Syntax**: `#[link(DefinitionName, ModelName)]` must match exactly
//! 4. **Check Repository Isolation**: Links across repositories need both in same repo
//! 5. **Use cargo-expand**: See exactly what code is being generated
//!
//! # Performance Characteristics
//!
//! The generated code is designed for:
//!
//! - **Zero-cost abstractions**: Trait impls compile to direct calls
//! - **Compile-time verification**: No runtime schema checks
//! - **Efficient serialization**: postcard binary format
//! - **Minimal allocations**: Clone only when necessary
